-- EFNS DEV account foundation. REVIEW credit quota and role assignments before execution.
-- Run role creation as USERADMIN, object creation as SYSADMIN, and the monitor as ACCOUNTADMIN.

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS EFNS_DEV_APP_OWNER COMMENT = 'Owns the EFNS DEV Streamlit app and runtime objects';
CREATE ROLE IF NOT EXISTS EFNS_DEV_DEPLOYER COMMENT = 'Deploys reviewed EFNS DEV application releases';
CREATE ROLE IF NOT EXISTS EFNS_DEV_ADMIN COMMENT = 'Can open EFNS; application table grants the Admin role';
CREATE ROLE IF NOT EXISTS EFNS_DEV_EDITOR COMMENT = 'Can open EFNS; application table grants the Data Editor role';
CREATE ROLE IF NOT EXISTS EFNS_DEV_DEVELOPER COMMENT = 'Can open EFNS; application table grants the Developer role';
CREATE ROLE IF NOT EXISTS EFNS_DEV_VIEWER COMMENT = 'Can open EFNS; application table grants the Reporting Viewer role';

GRANT ROLE EFNS_DEV_APP_OWNER TO ROLE EFNS_DEV_DEPLOYER;
GRANT ROLE EFNS_DEV_DEPLOYER TO ROLE SYSADMIN;
GRANT ROLE EFNS_DEV_ADMIN TO ROLE SYSADMIN;
GRANT ROLE EFNS_DEV_EDITOR TO ROLE SYSADMIN;
GRANT ROLE EFNS_DEV_DEVELOPER TO ROLE SYSADMIN;
GRANT ROLE EFNS_DEV_VIEWER TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS EFNS_DEV COMMENT = 'EFNS development environment; provisional model';
CREATE SCHEMA IF NOT EXISTS EFNS_DEV.RAW COMMENT = 'Source-preserving import records';
CREATE SCHEMA IF NOT EXISTS EFNS_DEV.CORE COMMENT = 'Provisional operational entities';
CREATE SCHEMA IF NOT EXISTS EFNS_DEV.REPORTING COMMENT = 'Report-ready views';
CREATE SCHEMA IF NOT EXISTS EFNS_DEV.SECURITY COMMENT = 'Application users and authorization';
CREATE SCHEMA IF NOT EXISTS EFNS_DEV.APP COMMENT = 'Application stages, audit events, and Streamlit object';

CREATE WAREHOUSE IF NOT EXISTS EFNS_DEV_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'X-Small EFNS development warehouse';

USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR IF NOT EXISTS EFNS_DEV_MONTHLY_MONITOR
  WITH CREDIT_QUOTA = 10
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;
ALTER RESOURCE MONITOR EFNS_DEV_MONTHLY_MONITOR SET CREDIT_QUOTA = 10;
ALTER WAREHOUSE EFNS_DEV_WH SET RESOURCE_MONITOR = EFNS_DEV_MONTHLY_MONITOR;
