-- EFNS DEV / PROVISIONAL core schema
-- Repeatable for a fresh or already-aligned DEV database. Existing legacy
-- schemas require a reviewed migration before this definition is applied.

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.ACCOUNT (
    ACCOUNT_ID VARCHAR(36) NOT NULL,
    REGISTRATION_NUMBER VARCHAR(64),
    ORGANIZATION_NAME VARCHAR(255) NOT NULL,
    ADDRESS_LINE1 VARCHAR(255),
    ADDRESS_LINE2 VARCHAR(255),
    ADDRESS_LINE3 VARCHAR(255),
    CITY VARCHAR(100),
    PROVINCE VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    COUNTRY_REGION VARCHAR(100),
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    CONTACT_NAME VARCHAR(255),
    CONTACT_PHONE VARCHAR(50),
    CONTACT_EMAIL VARCHAR(255),
    FAX VARCHAR(50),
    WEBSITE VARCHAR(500),
    LICENCE_NUMBER VARCHAR(64),
    PARENT_ACCOUNT_ID VARCHAR(36),
    GRADING_STATION_ACCOUNT_ID VARCHAR(36),
    PULLET_GROWER_ACCOUNT_ID VARCHAR(36),
    PROVINCE_OF_REGISTRATION VARCHAR(50),
    SPENT_FOWL_PLANS VARCHAR(2000),
    DEFAULT_ON_REPORTS BOOLEAN DEFAULT FALSE,
    NO_SVG BOOLEAN DEFAULT FALSE,
    DESCRIPTION VARCHAR(4000),
    PRODUCER_ROLE BOOLEAN DEFAULT FALSE,
    BREEDER_ROLE BOOLEAN DEFAULT FALSE,
    HATCHERY_ROLE BOOLEAN DEFAULT FALSE,
    PULLET_GROWER_ROLE BOOLEAN DEFAULT FALSE,
    GRADER_ROLE BOOLEAN DEFAULT FALSE,
    PROCESSOR_BREAKER_ROLE BOOLEAN DEFAULT FALSE,
    DISPOSAL_PLANT_ROLE BOOLEAN DEFAULT FALSE,
    UNREGULATED_ROLE BOOLEAN DEFAULT FALSE,
    PROV_BOARD_EFC_ROLE BOOLEAN DEFAULT FALSE,
    GOVERNMENT_ROLE BOOLEAN DEFAULT FALSE,
    VENDOR_ROLE BOOLEAN DEFAULT FALSE,
    RESEARCH_EXEMPT_ROLE BOOLEAN DEFAULT FALSE,
    SHIPPER_ROLE BOOLEAN DEFAULT FALSE,
    OTHER_ROLE BOOLEAN DEFAULT FALSE,
    STATUS VARCHAR(30) DEFAULT 'Active',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT FK_ACCOUNT_PARENT FOREIGN KEY (PARENT_ACCOUNT_ID)
        REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_ACCOUNT_GRADING_STATION FOREIGN KEY (GRADING_STATION_ACCOUNT_ID)
        REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_ACCOUNT_PULLET_GROWER FOREIGN KEY (PULLET_GROWER_ACCOUNT_ID)
        REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID)
)
COMMENT = 'DEV/provisional account model; Dataverse logical names are not confirmed.';

-- Dynamics labels this area "Other Addresses" and the view "Farm Locations".
-- This provisional child remains separate from regulated FACILITY records.
CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.FARM_LOCATION (
    FARM_LOCATION_ID VARCHAR(36) NOT NULL,
    ACCOUNT_ID VARCHAR(36) NOT NULL,
    LOCATION_NAME VARCHAR(255) NOT NULL,
    ADDRESS_1 VARCHAR(255),
    ADDRESS_2 VARCHAR(255),
    CITY VARCHAR(100),
    PROVINCE VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    PHONE VARCHAR(50),
    STATUS VARCHAR(30) DEFAULT 'Active',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_FARM_LOCATION PRIMARY KEY (FARM_LOCATION_ID),
    CONSTRAINT FK_FARM_LOCATION_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
        REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID)
)
COMMENT = 'DEV/provisional Account-owned Farm Location (Dynamics Other Address); distinct from Facility.';

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.FACILITY (
    FACILITY_ID VARCHAR(36) NOT NULL,
    ACCOUNT_ID VARCHAR(36) NOT NULL,
    FACILITY_NAME VARCHAR(255) NOT NULL,
    FACILITY_TYPE VARCHAR(50),
    STATUS VARCHAR(30) DEFAULT 'Active',
    ACTIVATION_DATE DATE,
    CONSTRUCTION_DATE DATE,
    CLOSURE_DATE DATE,
    DESTRUCTION_DATE DATE,
    INACTIVE_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_FACILITY PRIMARY KEY (FACILITY_ID),
    CONSTRAINT FK_FACILITY_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
        REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.FACILITY_DETAIL (
    FACILITY_DETAIL_ID VARCHAR(36) NOT NULL,
    FACILITY_ID VARCHAR(36) NOT NULL,
    DETAIL_NAME VARCHAR(255) NOT NULL,
    DETAIL_TYPE VARCHAR(100),
    STATUS VARCHAR(30) DEFAULT 'Active',
    COMMENTS VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_FACILITY_DETAIL PRIMARY KEY (FACILITY_DETAIL_ID),
    CONSTRAINT FK_FACILITY_DETAIL_FACILITY FOREIGN KEY (FACILITY_ID)
        REFERENCES EFNS_DEV.CORE.FACILITY (FACILITY_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.QUOTA_REGISTRATION (
    QUOTA_ID VARCHAR(36) NOT NULL,
    REGISTRATION_NUMBER VARCHAR(64) NOT NULL,
    ACCOUNT_ID VARCHAR(36) NOT NULL,
    QUOTA_NAME VARCHAR(255),
    QUOTA_TYPE VARCHAR(100) NOT NULL,
    STATUS VARCHAR(30) DEFAULT 'Active',
    EFFECTIVE_DATE DATE,
    END_DATE DATE,
    COMMENTS VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_QUOTA_REGISTRATION PRIMARY KEY (QUOTA_ID),
    CONSTRAINT FK_QUOTA_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
        REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID)
)
COMMENT = 'Quota allocation model and choice values are provisional.';

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.FLOCK (
    FLOCK_ID VARCHAR(36) NOT NULL,
    FLOCK_NUMBER VARCHAR(64) NOT NULL,
    ACCOUNT_ID VARCHAR(36) NOT NULL,
    FACILITY_ID VARCHAR(36) NOT NULL,
    FACILITY_DETAIL_ID VARCHAR(36),
    QUOTA_ID VARCHAR(36),
    FLOCK_QUOTA_TYPE VARCHAR(100),
    STATUS VARCHAR(30) DEFAULT 'Planned',
    CREATE_DELIVERY_TRANSACTION BOOLEAN DEFAULT FALSE,
    PERMIT_NUMBER VARCHAR(100) NOT NULL,
    PERMIT_DATE DATE,
    HATCH_DATE DATE NOT NULL,
    DATE_ORDERED DATE,
    BIRD_COUNT NUMBER(12,0) NOT NULL,
    EGG_COLOUR VARCHAR(50),
    BIRD_STRAIN VARCHAR(100),
    PLACEMENT_DATE DATE,
    EST_DISPOSAL DATE,
    DISPOSAL_DATE DATE,
    BIRDS_DISPOSED NUMBER(12,0) DEFAULT 0,
    BREEDER VARCHAR(255),
    HATCHERY VARCHAR(255),
    PULLET_GROWER VARCHAR(255),
    DISPOSAL_PLANT VARCHAR(255),
    DISPOSAL_METHOD VARCHAR(100),
    COMMENTS VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_FLOCK PRIMARY KEY (FLOCK_ID),
    CONSTRAINT FK_FLOCK_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
        REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_FLOCK_FACILITY FOREIGN KEY (FACILITY_ID)
        REFERENCES EFNS_DEV.CORE.FACILITY (FACILITY_ID),
    CONSTRAINT FK_FLOCK_DETAIL FOREIGN KEY (FACILITY_DETAIL_ID)
        REFERENCES EFNS_DEV.CORE.FACILITY_DETAIL (FACILITY_DETAIL_ID),
    CONSTRAINT FK_FLOCK_QUOTA FOREIGN KEY (QUOTA_ID)
        REFERENCES EFNS_DEV.CORE.QUOTA_REGISTRATION (QUOTA_ID),
    CONSTRAINT CK_FLOCK_BIRD_COUNT CHECK (BIRD_COUNT >= 0),
    CONSTRAINT CK_FLOCK_BIRDS_DISPOSED CHECK (BIRDS_DISPOSED >= 0)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.FLOCK_TRANSACTION (
    FLOCK_TRANSACTION_ID VARCHAR(36) NOT NULL,
    FLOCK_ID VARCHAR(36) NOT NULL,
    TRANSACTION_TYPE VARCHAR(100) NOT NULL,
    QUANTITY NUMBER(12,2) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_FLOCK_TRANSACTION PRIMARY KEY (FLOCK_TRANSACTION_ID),
    CONSTRAINT FK_FLOCK_TRANSACTION_FLOCK FOREIGN KEY (FLOCK_ID)
        REFERENCES EFNS_DEV.CORE.FLOCK (FLOCK_ID),
    CONSTRAINT CK_FLOCK_TRANSACTION_QUANTITY CHECK (QUANTITY > 0)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION (
    QUOTA_TRANSACTION_ID VARCHAR(36) NOT NULL,
    TRANSACTION_TYPE VARCHAR(50) NOT NULL,
    QUOTA_ID VARCHAR(36) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    END_DATE DATE,
    QUOTA_COUNT NUMBER(14,2) NOT NULL,
    OWNER_ACCOUNT_ID VARCHAR(36) NOT NULL,
    RELATED_ACCOUNT_ID VARCHAR(36) NOT NULL,
    RELATED_QUOTA_ID VARCHAR(36),
    RELATED_TRANSACTION_ID VARCHAR(36),
    PRICE NUMBER(14,2),
    QUOTA_LEASE_TYPE VARCHAR(100),
    COMMENTS VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_QUOTA_TRANSACTION PRIMARY KEY (QUOTA_TRANSACTION_ID),
    CONSTRAINT FK_QUOTA_TRANSACTION_QUOTA FOREIGN KEY (QUOTA_ID)
        REFERENCES EFNS_DEV.CORE.QUOTA_REGISTRATION (QUOTA_ID),
    CONSTRAINT FK_QUOTA_TRANSACTION_OWNER FOREIGN KEY (OWNER_ACCOUNT_ID)
        REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_QUOTA_TRANSACTION_RELATED_ACCOUNT FOREIGN KEY (RELATED_ACCOUNT_ID)
        REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT CK_QUOTA_TRANSACTION_COUNT CHECK (QUOTA_COUNT > 0)
)
COMMENT = 'Activity records only; no automatic quota balance calculation.';

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.SALMONELLA_TEST (
    SALMONELLA_TEST_ID VARCHAR(36) NOT NULL,
    FLOCK_ID VARCHAR(36) NOT NULL,
    ACCOUNT_ID VARCHAR(36) NOT NULL,
    PERMIT_NUMBER VARCHAR(100) NOT NULL,
    TESTING_DATE DATE NOT NULL,
    INSPECTOR VARCHAR(255),
    NUMBER_OF_SAMPLES NUMBER(10,0) NOT NULL,
    TEST_RESULT VARCHAR(50) NOT NULL,
    DATE_RESULT_SENT DATE,
    DATE_RECEIVED DATE,
    CASE_FILE_NUMBER VARCHAR(100),
    INVOICE_NUMBER VARCHAR(100),
    INVOICE_DATE DATE,
    COMMENTS VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_SALMONELLA_TEST PRIMARY KEY (SALMONELLA_TEST_ID),
    CONSTRAINT FK_SALMONELLA_TEST_FLOCK FOREIGN KEY (FLOCK_ID)
        REFERENCES EFNS_DEV.CORE.FLOCK (FLOCK_ID),
    CONSTRAINT FK_SALMONELLA_TEST_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
        REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT CK_SALMONELLA_SAMPLE_COUNT CHECK (NUMBER_OF_SAMPLES > 0)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE (
    SALMONELLA_TEST_SAMPLE_ID VARCHAR(36) NOT NULL,
    SALMONELLA_TEST_ID VARCHAR(36) NOT NULL,
    SAMPLE_REFERENCE VARCHAR(100),
    COMMENTS VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_SALMONELLA_TEST_SAMPLE PRIMARY KEY (SALMONELLA_TEST_SAMPLE_ID),
    CONSTRAINT FK_SALMONELLA_SAMPLE_TEST FOREIGN KEY (SALMONELLA_TEST_ID)
        REFERENCES EFNS_DEV.CORE.SALMONELLA_TEST (SALMONELLA_TEST_ID)
)
COMMENT = 'Sample extension point; business fields remain provisional.';
