-- EFNS DEV / PROVISIONAL import and production schema
-- Standard Snowflake tables are used for RAW history and reporting sources.

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.IMPORT_BATCH (
    IMPORT_ID VARCHAR(36) NOT NULL,
    FILENAME VARCHAR(500) NOT NULL,
    SOURCE VARCHAR(255),
    FILE_HASH VARCHAR(64),
    FILE_SIZE_BYTES NUMBER(18,0),
    WORKSHEET_NAME VARCHAR(255),
    REPORTING_YEAR NUMBER(4,0),
    REPORTING_WEEK NUMBER(2,0),
    SOURCE_RECORD_COUNT NUMBER(18,0) DEFAULT 0,
    ROW_COUNT NUMBER(18,0) DEFAULT 0,
    ERROR_COUNT NUMBER(18,0) DEFAULT 0,
    STATUS VARCHAR(50) DEFAULT 'Uploaded',
    NOTES VARCHAR(2000),
    UPLOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_IMPORT_BATCH PRIMARY KEY (IMPORT_ID),
    CONSTRAINT UQ_IMPORT_BATCH_HASH UNIQUE (FILE_HASH)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.IMPORT_RAW_ROW (
    RAW_ROW_ID VARCHAR(36) NOT NULL,
    IMPORT_ID VARCHAR(36) NOT NULL,
    SOURCE_ROW_NUMBER NUMBER(18,0) NOT NULL,
    RAW_DATA VARIANT NOT NULL,
    VALIDATION_STATUS VARCHAR(50) DEFAULT 'PENDING',
    MATCH_STATUS VARCHAR(50) DEFAULT 'UNMATCHED',
    VALIDATION_MESSAGES VARIANT,
    MATCHED_ACCOUNT_ID VARCHAR(36),
    MATCHED_FACILITY_ID VARCHAR(36),
    MATCHED_FLOCK_ID VARCHAR(36),
    MATCH_CONFIRMED_AT TIMESTAMP_NTZ,
    MATCH_CONFIRMED_BY VARCHAR(255),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_IMPORT_RAW_ROW PRIMARY KEY (RAW_ROW_ID),
    CONSTRAINT FK_RAW_ROW_IMPORT FOREIGN KEY (IMPORT_ID)
        REFERENCES EFNS_DEV.RAW.IMPORT_BATCH (IMPORT_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD (
    PRODUCTION_ID VARCHAR(36) NOT NULL,
    IMPORT_ID VARCHAR(36) NOT NULL,
    PRODUCER_ACCOUNT_ID VARCHAR(36),
    GRADER_ACCOUNT_ID VARCHAR(36),
    FACILITY_ID VARCHAR(36),
    FLOCK_ID VARCHAR(36),
    GRADER_NAME VARCHAR(255),
    PRODUCER_NUMBER VARCHAR(100),
    GRADER_NUMBER VARCHAR(100),
    BARN_IDENTITY VARCHAR(100),
    SOURCE_WEEK_CODE VARCHAR(20),
    REPORTING_YEAR NUMBER(4,0),
    REPORTING_WEEK NUMBER(2,0),
    MARKETING_TYPE VARCHAR(100),
    HOUSING_SYSTEM VARCHAR(100),
    EGG_TYPE VARCHAR(100),
    EGG_COLOUR VARCHAR(50),
    FLOCK_AGE NUMBER(10,0),
    NET_WEIGHT NUMBER(18,4),
    NET_BOXES NUMBER(18,4),
    NET_PER_BOX NUMBER(18,4),
    JUMBO NUMBER(18,4),
    EXTRA_LARGE NUMBER(18,4),
    LARGE NUMBER(18,4),
    MEDIUM NUMBER(18,4),
    SMALL NUMBER(18,4),
    PEEWEE NUMBER(18,4),
    GRADE_B NUMBER(18,4),
    GRADE_C NUMBER(18,4),
    CRACKS NUMBER(18,4),
    NEST_RUN NUMBER(18,4),
    NEST_RUN_25_PLUS NUMBER(18,4),
    NEST_RUN_24_PLUS NUMBER(18,4),
    NEST_RUN_23_PLUS NUMBER(18,4),
    NEST_RUN_22_PLUS NUMBER(18,4),
    NEST_RUN_21_PLUS NUMBER(18,4),
    NEST_RUN_20_PLUS NUMBER(18,4),
    NEST_RUN_19_PLUS NUMBER(18,4),
    NEST_RUN_18_PLUS NUMBER(18,4),
    NEST_RUN_17_PLUS NUMBER(18,4),
    OTHER_LEVIABLE NUMBER(18,4),
    OTHER_NON_LEVIABLE NUMBER(18,4),
    FARM_GATE_SALES NUMBER(18,4),
    ON_FARM_CONSUMPTION NUMBER(18,4),
    SUBTOTAL NUMBER(18,4),
    REJECTS NUMBER(18,4),
    LEAKERS NUMBER(18,4),
    TOTAL NUMBER(18,4),
    TOTAL_RECEIVED NUMBER(18,4),
    REJECTED NUMBER(18,4),
    LOSS NUMBER(18,4),
    LEGACY_REJECT_LOSS_TOTAL NUMBER(18,4),
    TOTAL_ACCEPTED NUMBER(18,4),
    SOURCE_TYPE VARCHAR(50) NOT NULL,
    MATCH_STATUS VARCHAR(50) DEFAULT 'UNMATCHED',
    SOURCE_ROW_NUMBER NUMBER(18,0),
    MATCH_CONFIRMED_AT TIMESTAMP_NTZ,
    MATCH_CONFIRMED_BY VARCHAR(255),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_PRODUCTION_RECORD PRIMARY KEY (PRODUCTION_ID),
    CONSTRAINT FK_PRODUCTION_IMPORT FOREIGN KEY (IMPORT_ID)
        REFERENCES EFNS_DEV.RAW.IMPORT_BATCH (IMPORT_ID),
    CONSTRAINT FK_PRODUCTION_ACCOUNT FOREIGN KEY (PRODUCER_ACCOUNT_ID)
        REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_PRODUCTION_FACILITY FOREIGN KEY (FACILITY_ID)
        REFERENCES EFNS_DEV.CORE.FACILITY (FACILITY_ID),
    CONSTRAINT FK_PRODUCTION_FLOCK FOREIGN KEY (FLOCK_ID)
        REFERENCES EFNS_DEV.CORE.FLOCK (FLOCK_ID)
)
COMMENT = 'Normalized production; EIMS rows remain UNMATCHED until confirmed.';

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.PRODUCTION_SIZE_BREAKDOWN (
    SIZE_BREAKDOWN_ID VARCHAR(36) NOT NULL,
    PRODUCTION_ID VARCHAR(36) NOT NULL,
    SIZE_BAND VARCHAR(50) NOT NULL,
    QUANTITY NUMBER(18,4),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_PRODUCTION_SIZE_BREAKDOWN PRIMARY KEY (SIZE_BREAKDOWN_ID),
    CONSTRAINT FK_SIZE_PRODUCTION FOREIGN KEY (PRODUCTION_ID)
        REFERENCES EFNS_DEV.CORE.PRODUCTION_RECORD (PRODUCTION_ID)
);
