-- EFNS application authorization and audit persistence for Streamlit in Snowflake.
-- Standard tables are intentional for the DEV foundation. Role/domain constraints
-- are enforced by application services and covered by offline tests.

USE ROLE SYSADMIN;
USE DATABASE EFNS_DEV;

CREATE TABLE IF NOT EXISTS EFNS_DEV.SECURITY.APP_USER (
    USER_ID VARCHAR(36) NOT NULL,
    EMAIL VARCHAR(320) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    LAST_LOGIN_AT TIMESTAMP_TZ,
    CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()),
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()),
    CONSTRAINT PK_APP_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_APP_USER_EMAIL UNIQUE (EMAIL)
)
COMMENT = 'EFNS application roles for Snowflake-authenticated @nsegg.ca viewers';

CREATE TABLE IF NOT EXISTS EFNS_DEV.APP.AUDIT_EVENT (
    AUDIT_ID VARCHAR(36) NOT NULL,
    ACTOR_USER_ID VARCHAR(36),
    ACTOR_EMAIL VARCHAR(320) NOT NULL,
    ACTION VARCHAR(100) NOT NULL,
    ENTITY_TYPE VARCHAR(100) NOT NULL,
    ENTITY_ID VARCHAR(100),
    DETAILS VARIANT,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()),
    CONSTRAINT PK_AUDIT_EVENT PRIMARY KEY (AUDIT_ID)
)
COMMENT = 'Append-only EFNS application audit events using viewer email';
