-- Least-privilege runtime and deployment grants. Run after 02-05 table scripts.

USE ROLE SECURITYADMIN;

-- Remove grants from an earlier DEV draft before applying the table-specific
-- runtime policy below. Keeping these revokes makes the script safe to use when
-- upgrading an environment that received the former database-wide grants.
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE EFNS_DEV FROM ROLE EFNS_DEV_APP_OWNER;
REVOKE SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE EFNS_DEV FROM ROLE EFNS_DEV_APP_OWNER;
REVOKE SELECT ON ALL VIEWS IN DATABASE EFNS_DEV FROM ROLE EFNS_DEV_APP_OWNER;
REVOKE SELECT ON FUTURE VIEWS IN DATABASE EFNS_DEV FROM ROLE EFNS_DEV_APP_OWNER;
REVOKE USAGE ON FUTURE SCHEMAS IN DATABASE EFNS_DEV FROM ROLE EFNS_DEV_APP_OWNER;

GRANT USAGE ON WAREHOUSE EFNS_DEV_WH TO ROLE EFNS_DEV_APP_OWNER;
GRANT USAGE ON DATABASE EFNS_DEV TO ROLE EFNS_DEV_APP_OWNER;
GRANT USAGE ON SCHEMA EFNS_DEV.RAW TO ROLE EFNS_DEV_APP_OWNER;
GRANT USAGE ON SCHEMA EFNS_DEV.CORE TO ROLE EFNS_DEV_APP_OWNER;
GRANT USAGE ON SCHEMA EFNS_DEV.REPORTING TO ROLE EFNS_DEV_APP_OWNER;
GRANT USAGE ON SCHEMA EFNS_DEV.SECURITY TO ROLE EFNS_DEV_APP_OWNER;
GRANT USAGE ON SCHEMA EFNS_DEV.APP TO ROLE EFNS_DEV_APP_OWNER;

-- Operational CRUD used by SnowflakeRepository.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE EFNS_DEV.CORE.ACCOUNT TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE EFNS_DEV.CORE.FACILITY TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE EFNS_DEV.CORE.FACILITY_DETAIL TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE EFNS_DEV.CORE.FLOCK TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE EFNS_DEV.CORE.FLOCK_TRANSACTION TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE EFNS_DEV.CORE.QUOTA_REGISTRATION TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE EFNS_DEV.CORE.QUOTA_TRANSACTION TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE EFNS_DEV.CORE.SALMONELLA_TEST TO ROLE EFNS_DEV_APP_OWNER;

-- Read-only extension data and append-only production import targets.
GRANT SELECT ON TABLE EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT ON TABLE EFNS_DEV.CORE.PRODUCTION_RECORD TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE ON TABLE EFNS_DEV.RAW.IMPORT_BATCH TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT ON TABLE EFNS_DEV.RAW.IMPORT_RAW_ROW TO ROLE EFNS_DEV_APP_OWNER;

-- The current repository reads only this reporting view.
GRANT SELECT ON VIEW EFNS_DEV.REPORTING.VW_PRODUCTION_SUMMARY TO ROLE EFNS_DEV_APP_OWNER;

-- Snowflake viewer authorization and append-only audit persistence.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE EFNS_DEV.SECURITY.APP_USER TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT ON TABLE EFNS_DEV.APP.AUDIT_EVENT TO ROLE EFNS_DEV_APP_OWNER;
REVOKE UPDATE, DELETE ON TABLE EFNS_DEV.APP.AUDIT_EVENT FROM ROLE EFNS_DEV_APP_OWNER;

-- Deliberately omit future-object grants. In particular, no future grant may
-- restore UPDATE or DELETE on APP.AUDIT_EVENT if that table is recreated.
GRANT CREATE STAGE, CREATE STREAMLIT ON SCHEMA EFNS_DEV.APP TO ROLE EFNS_DEV_APP_OWNER;

GRANT USAGE ON DATABASE EFNS_DEV TO ROLE EFNS_DEV_DEPLOYER;
GRANT USAGE ON SCHEMA EFNS_DEV.APP TO ROLE EFNS_DEV_DEPLOYER;
GRANT USAGE ON WAREHOUSE EFNS_DEV_WH TO ROLE EFNS_DEV_DEPLOYER;

USE ROLE EFNS_DEV_APP_OWNER;
CREATE STAGE IF NOT EXISTS EFNS_DEV.APP.EFNS_STREAMLIT_STAGE
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Reviewed EFNS Streamlit deployment artifacts';
