-- Bootstrap exactly one real EFNS Admin before opening the app.
-- Replace both placeholder values. If the email is not @nsegg.ca, no row is inserted.

USE ROLE EFNS_DEV_DEPLOYER;
SET EFNS_INITIAL_ADMIN_EMAIL = '<INITIAL_ADMIN_EMAIL>';
SET EFNS_INITIAL_ADMIN_NAME = '<INITIAL_ADMIN_DISPLAY_NAME>';

INSERT INTO EFNS_DEV.SECURITY.APP_USER
    (USER_ID, EMAIL, DISPLAY_NAME, ROLE, ACTIVE, CREATED_AT, UPDATED_AT)
SELECT UUID_STRING(), LOWER(TRIM($EFNS_INITIAL_ADMIN_EMAIL)), TRIM($EFNS_INITIAL_ADMIN_NAME),
       'Admin', TRUE, CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()),
       CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())
WHERE LOWER(TRIM($EFNS_INITIAL_ADMIN_EMAIL)) LIKE '%@nsegg.ca'
  AND NOT EXISTS (
      SELECT 1 FROM EFNS_DEV.SECURITY.APP_USER
      WHERE LOWER(EMAIL) = LOWER(TRIM($EFNS_INITIAL_ADMIN_EMAIL))
  );
