-- EFNS DEV ONLY - FULLY SYNTHETIC, FICTIONAL DATA
--
-- This seed contains no real producer, employee, facility, or EIMS records.
-- Every owned identifier and descriptive marker begins with DEV_SYNTH.
-- Expected connected rows: 5 accounts, 8 facilities, 12 flocks,
-- 20 flock transactions, 6 quota registrations, 10 quota transactions,
-- 10 salmonella tests, 1 import batch, and 100 production records.
--
-- Run only after sql/02_core_tables.sql, sql/03_production_tables.sql, and
-- sql/04_reporting_views.sql.
-- Re-running is safe: MERGE inserts only identifiers that do not already exist.

USE ROLE SYSADMIN;
USE WAREHOUSE EFNS_DEV_WH;
USE DATABASE EFNS_DEV;

EXECUTE IMMEDIATE $$
BEGIN
    BEGIN TRANSACTION;

    MERGE INTO EFNS_DEV.CORE.ACCOUNT AS target
    USING (
        SELECT
            'DEV_SYNTH_ACCOUNT_' || LPAD(TO_VARCHAR(n), 3, '0') AS ACCOUNT_ID,
            'DEV_SYNTH_REG_' || LPAD(TO_VARCHAR(n), 3, '0') AS REGISTRATION_NUMBER,
            'DEV_SYNTH Fictional Producer ' || TO_VARCHAR(n) AS ORGANIZATION_NAME,
            'Synthetic City ' || TO_VARCHAR(n) AS CITY,
            'NS' AS PROVINCE,
            'B0B 0B' || TO_VARCHAR(n) AS POSTAL_CODE,
            'Canada' AS COUNTRY_REGION,
            'dev-synth-' || TO_VARCHAR(n) || '@example.invalid' AS CONTACT_EMAIL,
            'DEV_SYNTH_LIC_' || LPAD(TO_VARCHAR(n), 3, '0') AS LICENCE_NUMBER,
            'Fully fictional DEV_SYNTH account for Snowflake smoke testing.' AS DESCRIPTION,
            TRUE AS PRODUCER_ROLE,
            IFF(n = 5, TRUE, FALSE) AS GRADER_ROLE,
            'Active' AS STATUS,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS CREATED_AT,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS UPDATED_AT
        FROM (
            SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS n
            FROM TABLE(GENERATOR(ROWCOUNT => 5))
        )
    ) AS source
        ON target.ACCOUNT_ID = source.ACCOUNT_ID
    WHEN NOT MATCHED THEN INSERT (
        ACCOUNT_ID, REGISTRATION_NUMBER, ORGANIZATION_NAME, CITY, PROVINCE,
        POSTAL_CODE, COUNTRY_REGION, CONTACT_EMAIL, LICENCE_NUMBER, DESCRIPTION,
        PRODUCER_ROLE, GRADER_ROLE, STATUS, CREATED_AT, UPDATED_AT
    ) VALUES (
        source.ACCOUNT_ID, source.REGISTRATION_NUMBER, source.ORGANIZATION_NAME,
        source.CITY, source.PROVINCE, source.POSTAL_CODE, source.COUNTRY_REGION,
        source.CONTACT_EMAIL, source.LICENCE_NUMBER, source.DESCRIPTION,
        source.PRODUCER_ROLE, source.GRADER_ROLE, source.STATUS,
        source.CREATED_AT, source.UPDATED_AT
    );

    MERGE INTO EFNS_DEV.CORE.FACILITY AS target
    USING (
        SELECT
            'DEV_SYNTH_FACILITY_' || LPAD(TO_VARCHAR(n), 3, '0') AS FACILITY_ID,
            'DEV_SYNTH_ACCOUNT_' || LPAD(TO_VARCHAR(
                CASE WHEN n <= 6 THEN CEIL(n / 2) WHEN n = 7 THEN 4 ELSE 5 END
            ), 3, '0') AS ACCOUNT_ID,
            'DEV_SYNTH Fictional Facility ' || TO_VARCHAR(n) AS FACILITY_NAME,
            CASE MOD(n - 1, 3) WHEN 0 THEN 'Layer' WHEN 1 THEN 'Pullet' ELSE 'Other' END AS FACILITY_TYPE,
            'Active' AS STATUS,
            DATEADD(day, n, DATE '2025-01-01') AS ACTIVATION_DATE,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS CREATED_AT,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS UPDATED_AT
        FROM (
            SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS n
            FROM TABLE(GENERATOR(ROWCOUNT => 8))
        )
    ) AS source
        ON target.FACILITY_ID = source.FACILITY_ID
    WHEN NOT MATCHED THEN INSERT (
        FACILITY_ID, ACCOUNT_ID, FACILITY_NAME, FACILITY_TYPE, STATUS,
        ACTIVATION_DATE, CREATED_AT, UPDATED_AT
    ) VALUES (
        source.FACILITY_ID, source.ACCOUNT_ID, source.FACILITY_NAME,
        source.FACILITY_TYPE, source.STATUS, source.ACTIVATION_DATE,
        source.CREATED_AT, source.UPDATED_AT
    );

    MERGE INTO EFNS_DEV.CORE.QUOTA_REGISTRATION AS target
    USING (
        SELECT
            'DEV_SYNTH_QUOTA_' || LPAD(TO_VARCHAR(n), 3, '0') AS QUOTA_ID,
            'DEV_SYNTH_QUOTA_REG_' || LPAD(TO_VARCHAR(n), 3, '0') AS REGISTRATION_NUMBER,
            'DEV_SYNTH_ACCOUNT_' || LPAD(TO_VARCHAR(IFF(n <= 2, 1, n - 1)), 3, '0') AS ACCOUNT_ID,
            'DEV_SYNTH Fictional Quota ' || TO_VARCHAR(n) AS QUOTA_NAME,
            CASE n
                WHEN 2 THEN 'Commercial Pullet'
                WHEN 4 THEN 'Non-Commercial Pullet'
                ELSE 'Egg Production'
            END AS QUOTA_TYPE,
            'Active' AS STATUS,
            DATE '2025-01-01' AS EFFECTIVE_DATE,
            DATE '2027-12-31' AS END_DATE,
            'Fully fictional DEV_SYNTH quota registration.' AS COMMENTS,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS CREATED_AT,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS UPDATED_AT
        FROM (
            SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS n
            FROM TABLE(GENERATOR(ROWCOUNT => 6))
        )
    ) AS source
        ON target.QUOTA_ID = source.QUOTA_ID
    WHEN NOT MATCHED THEN INSERT (
        QUOTA_ID, REGISTRATION_NUMBER, ACCOUNT_ID, QUOTA_NAME, QUOTA_TYPE,
        STATUS, EFFECTIVE_DATE, END_DATE, COMMENTS, CREATED_AT, UPDATED_AT
    ) VALUES (
        source.QUOTA_ID, source.REGISTRATION_NUMBER, source.ACCOUNT_ID,
        source.QUOTA_NAME, source.QUOTA_TYPE, source.STATUS, source.EFFECTIVE_DATE,
        source.END_DATE, source.COMMENTS, source.CREATED_AT, source.UPDATED_AT
    );

    MERGE INTO EFNS_DEV.CORE.FLOCK AS target
    USING (
        SELECT
            'DEV_SYNTH_FLOCK_' || LPAD(TO_VARCHAR(n), 3, '0') AS FLOCK_ID,
            'DEV_SYNTH_FLOCK_NO_' || LPAD(TO_VARCHAR(n), 3, '0') AS FLOCK_NUMBER,
            'DEV_SYNTH_ACCOUNT_' || LPAD(TO_VARCHAR(
                CASE WHEN n <= 3 THEN 1 WHEN n <= 5 THEN 2 WHEN n <= 8 THEN 3 WHEN n <= 10 THEN 4 ELSE 5 END
            ), 3, '0') AS ACCOUNT_ID,
            'DEV_SYNTH_FACILITY_' || LPAD(TO_VARCHAR(
                CASE n WHEN 1 THEN 1 WHEN 2 THEN 2 WHEN 3 THEN 1 WHEN 4 THEN 3
                    WHEN 5 THEN 4 WHEN 6 THEN 5 WHEN 7 THEN 6 WHEN 8 THEN 5
                    WHEN 9 THEN 7 WHEN 10 THEN 7 ELSE 8 END
            ), 3, '0') AS FACILITY_ID,
            'DEV_SYNTH_QUOTA_' || LPAD(TO_VARCHAR(
                CASE WHEN n = 2 THEN 2 WHEN n <= 3 THEN 1 WHEN n <= 5 THEN 3
                    WHEN n <= 8 THEN 4 WHEN n <= 10 THEN 5 ELSE 6 END
            ), 3, '0') AS QUOTA_ID,
            CASE WHEN n = 2 THEN 'Commercial Pullet'
                WHEN n BETWEEN 6 AND 8 THEN 'Non-Commercial Pullet'
                ELSE 'Egg Production' END AS FLOCK_QUOTA_TYPE,
            CASE WHEN n <= 9 THEN 'Active' WHEN n <= 11 THEN 'Planned' ELSE 'Depopulated' END AS STATUS,
            FALSE AS CREATE_DELIVERY_TRANSACTION,
            'DEV_SYNTH_PERMIT_' || LPAD(TO_VARCHAR(n), 3, '0') AS PERMIT_NUMBER,
            DATEADD(day, n, DATE '2025-01-01') AS PERMIT_DATE,
            DATEADD(day, n, DATE '2025-01-15') AS HATCH_DATE,
            10000 + (n * 250) AS BIRD_COUNT,
            IFF(MOD(n, 2) = 0, 'Brown', 'White') AS EGG_COLOUR,
            'DEV_SYNTH Strain ' || TO_VARCHAR(MOD(n - 1, 3) + 1) AS BIRD_STRAIN,
            DATEADD(day, n, DATE '2025-05-15') AS PLACEMENT_DATE,
            DATEADD(day, n, DATE '2027-01-15') AS EST_DISPOSAL,
            IFF(n = 12, DATEADD(day, n, DATE '2026-08-01'), NULL) AS DISPOSAL_DATE,
            IFF(n = 12, 13000, 0) AS BIRDS_DISPOSED,
            'Fully fictional DEV_SYNTH flock.' AS COMMENTS,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS CREATED_AT,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS UPDATED_AT
        FROM (
            SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS n
            FROM TABLE(GENERATOR(ROWCOUNT => 12))
        )
    ) AS source
        ON target.FLOCK_ID = source.FLOCK_ID
    WHEN NOT MATCHED THEN INSERT (
        FLOCK_ID, FLOCK_NUMBER, ACCOUNT_ID, FACILITY_ID, QUOTA_ID,
        FLOCK_QUOTA_TYPE, STATUS, CREATE_DELIVERY_TRANSACTION, PERMIT_NUMBER,
        PERMIT_DATE, HATCH_DATE, BIRD_COUNT, EGG_COLOUR, BIRD_STRAIN,
        PLACEMENT_DATE, EST_DISPOSAL, DISPOSAL_DATE, BIRDS_DISPOSED, COMMENTS,
        CREATED_AT, UPDATED_AT
    ) VALUES (
        source.FLOCK_ID, source.FLOCK_NUMBER, source.ACCOUNT_ID,
        source.FACILITY_ID, source.QUOTA_ID, source.FLOCK_QUOTA_TYPE,
        source.STATUS, source.CREATE_DELIVERY_TRANSACTION, source.PERMIT_NUMBER,
        source.PERMIT_DATE, source.HATCH_DATE, source.BIRD_COUNT,
        source.EGG_COLOUR, source.BIRD_STRAIN, source.PLACEMENT_DATE,
        source.EST_DISPOSAL, source.DISPOSAL_DATE, source.BIRDS_DISPOSED,
        source.COMMENTS, source.CREATED_AT, source.UPDATED_AT
    );

    MERGE INTO EFNS_DEV.CORE.FLOCK_TRANSACTION AS target
    USING (
        SELECT
            'DEV_SYNTH_FLOCK_TX_' || LPAD(TO_VARCHAR(n), 3, '0') AS FLOCK_TRANSACTION_ID,
            'DEV_SYNTH_FLOCK_' || LPAD(TO_VARCHAR(MOD(n - 1, 12) + 1), 3, '0') AS FLOCK_ID,
            CASE MOD(n - 1, 4) WHEN 0 THEN 'Count' WHEN 1 THEN 'Delivery' WHEN 2 THEN 'Removal' ELSE 'Sale' END AS TRANSACTION_TYPE,
            100 + (n * 10) AS QUANTITY,
            DATEADD(day, n, DATE '2026-01-01') AS TRANSACTION_DATE,
            'Fully fictional DEV_SYNTH flock transaction.' AS NOTES,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS CREATED_AT,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS UPDATED_AT
        FROM (
            SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS n
            FROM TABLE(GENERATOR(ROWCOUNT => 20))
        )
    ) AS source
        ON target.FLOCK_TRANSACTION_ID = source.FLOCK_TRANSACTION_ID
    WHEN NOT MATCHED THEN INSERT (
        FLOCK_TRANSACTION_ID, FLOCK_ID, TRANSACTION_TYPE, QUANTITY,
        TRANSACTION_DATE, NOTES, CREATED_AT, UPDATED_AT
    ) VALUES (
        source.FLOCK_TRANSACTION_ID, source.FLOCK_ID, source.TRANSACTION_TYPE,
        source.QUANTITY, source.TRANSACTION_DATE, source.NOTES,
        source.CREATED_AT, source.UPDATED_AT
    );

    MERGE INTO EFNS_DEV.CORE.QUOTA_TRANSACTION AS target
    USING (
        SELECT
            'DEV_SYNTH_QUOTA_TX_' || LPAD(TO_VARCHAR(n), 3, '0') AS QUOTA_TRANSACTION_ID,
            CASE MOD(n - 1, 4) WHEN 0 THEN 'Purchase' WHEN 1 THEN 'Sale' WHEN 2 THEN 'Lease In' ELSE 'Lease Out' END AS TRANSACTION_TYPE,
            'DEV_SYNTH_QUOTA_' || LPAD(TO_VARCHAR(MOD(n - 1, 6) + 1), 3, '0') AS QUOTA_ID,
            DATEADD(day, n, DATE '2026-02-01') AS EFFECTIVE_DATE,
            IFF(MOD(n - 1, 4) >= 2, DATEADD(day, n, DATE '2027-02-01'), NULL) AS END_DATE,
            250 + (n * 25) AS QUOTA_COUNT,
            'DEV_SYNTH_ACCOUNT_' || LPAD(TO_VARCHAR(
                CASE MOD(n - 1, 6) + 1 WHEN 1 THEN 1 WHEN 2 THEN 1
                    WHEN 3 THEN 2 WHEN 4 THEN 3 WHEN 5 THEN 4 ELSE 5 END
            ), 3, '0') AS OWNER_ACCOUNT_ID,
            'DEV_SYNTH_ACCOUNT_' || LPAD(TO_VARCHAR(MOD(n, 5) + 1), 3, '0') AS RELATED_ACCOUNT_ID,
            1000 + (n * 125) AS PRICE,
            IFF(MOD(n - 1, 4) >= 2, 'Fixed Term', NULL) AS QUOTA_LEASE_TYPE,
            'Fully fictional DEV_SYNTH quota transaction.' AS COMMENTS,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS CREATED_AT,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS UPDATED_AT
        FROM (
            SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS n
            FROM TABLE(GENERATOR(ROWCOUNT => 10))
        )
    ) AS source
        ON target.QUOTA_TRANSACTION_ID = source.QUOTA_TRANSACTION_ID
    WHEN NOT MATCHED THEN INSERT (
        QUOTA_TRANSACTION_ID, TRANSACTION_TYPE, QUOTA_ID, EFFECTIVE_DATE,
        END_DATE, QUOTA_COUNT, OWNER_ACCOUNT_ID, RELATED_ACCOUNT_ID, PRICE,
        QUOTA_LEASE_TYPE, COMMENTS, CREATED_AT, UPDATED_AT
    ) VALUES (
        source.QUOTA_TRANSACTION_ID, source.TRANSACTION_TYPE, source.QUOTA_ID,
        source.EFFECTIVE_DATE, source.END_DATE, source.QUOTA_COUNT,
        source.OWNER_ACCOUNT_ID, source.RELATED_ACCOUNT_ID, source.PRICE,
        source.QUOTA_LEASE_TYPE, source.COMMENTS, source.CREATED_AT,
        source.UPDATED_AT
    );

    MERGE INTO EFNS_DEV.CORE.SALMONELLA_TEST AS target
    USING (
        SELECT
            'DEV_SYNTH_SALMONELLA_' || LPAD(TO_VARCHAR(g.n), 3, '0') AS SALMONELLA_TEST_ID,
            f.FLOCK_ID,
            f.ACCOUNT_ID,
            f.PERMIT_NUMBER,
            DATEADD(day, g.n, DATE '2026-03-01') AS TESTING_DATE,
            'DEV_SYNTH Inspector ' || TO_VARCHAR(MOD(g.n - 1, 3) + 1) AS INSPECTOR,
            4 + MOD(g.n, 4) AS NUMBER_OF_SAMPLES,
            CASE MOD(g.n - 1, 4) WHEN 0 THEN 'Pending' WHEN 1 THEN 'Negative' WHEN 2 THEN 'Positive' ELSE 'Inconclusive' END AS TEST_RESULT,
            DATEADD(day, g.n + 3, DATE '2026-03-01') AS DATE_RESULT_SENT,
            DATEADD(day, g.n + 1, DATE '2026-03-01') AS DATE_RECEIVED,
            'DEV_SYNTH_CASE_' || LPAD(TO_VARCHAR(g.n), 3, '0') AS CASE_FILE_NUMBER,
            'DEV_SYNTH_INV_' || LPAD(TO_VARCHAR(g.n), 3, '0') AS INVOICE_NUMBER,
            DATEADD(day, g.n + 4, DATE '2026-03-01') AS INVOICE_DATE,
            'Fully fictional DEV_SYNTH salmonella test.' AS COMMENTS,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS CREATED_AT,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS UPDATED_AT
        FROM (
            SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS n
            FROM TABLE(GENERATOR(ROWCOUNT => 10))
        ) AS g
        JOIN EFNS_DEV.CORE.FLOCK AS f
          ON f.FLOCK_ID = 'DEV_SYNTH_FLOCK_' || LPAD(TO_VARCHAR(g.n), 3, '0')
    ) AS source
        ON target.SALMONELLA_TEST_ID = source.SALMONELLA_TEST_ID
    WHEN NOT MATCHED THEN INSERT (
        SALMONELLA_TEST_ID, FLOCK_ID, ACCOUNT_ID, PERMIT_NUMBER, TESTING_DATE,
        INSPECTOR, NUMBER_OF_SAMPLES, TEST_RESULT, DATE_RESULT_SENT,
        DATE_RECEIVED, CASE_FILE_NUMBER, INVOICE_NUMBER, INVOICE_DATE, COMMENTS,
        CREATED_AT, UPDATED_AT
    ) VALUES (
        source.SALMONELLA_TEST_ID, source.FLOCK_ID, source.ACCOUNT_ID,
        source.PERMIT_NUMBER, source.TESTING_DATE, source.INSPECTOR,
        source.NUMBER_OF_SAMPLES, source.TEST_RESULT, source.DATE_RESULT_SENT,
        source.DATE_RECEIVED, source.CASE_FILE_NUMBER, source.INVOICE_NUMBER,
        source.INVOICE_DATE, source.COMMENTS, source.CREATED_AT, source.UPDATED_AT
    );

    MERGE INTO EFNS_DEV.RAW.IMPORT_BATCH AS target
    USING (
        SELECT
            'DEV_SYNTH_IMPORT_001' AS IMPORT_ID,
            'DEV_SYNTH_PRODUCTION_2026.csv' AS FILENAME,
            'DEV_SYNTH' AS SOURCE,
            'd3e7a92f8b50437cac57f9da730e841dd3e7a92f8b50437cac57f9da730e841d' AS FILE_HASH,
            0 AS FILE_SIZE_BYTES,
            'DEV_SYNTH' AS WORKSHEET_NAME,
            2026 AS REPORTING_YEAR,
            1 AS REPORTING_WEEK,
            100 AS SOURCE_RECORD_COUNT,
            100 AS ROW_COUNT,
            0 AS ERROR_COUNT,
            'Committed' AS STATUS,
            'Fully fictional DEV_SYNTH batch created directly by the reviewed seed.' AS NOTES,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS UPLOAD_TIMESTAMP,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS CREATED_AT,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS UPDATED_AT
    ) AS source
        ON target.IMPORT_ID = source.IMPORT_ID
    WHEN NOT MATCHED THEN INSERT (
        IMPORT_ID, FILENAME, SOURCE, FILE_HASH, FILE_SIZE_BYTES, WORKSHEET_NAME,
        REPORTING_YEAR, REPORTING_WEEK, SOURCE_RECORD_COUNT, ROW_COUNT,
        ERROR_COUNT, STATUS, NOTES, UPLOAD_TIMESTAMP, CREATED_AT, UPDATED_AT
    ) VALUES (
        source.IMPORT_ID, source.FILENAME, source.SOURCE, source.FILE_HASH,
        source.FILE_SIZE_BYTES, source.WORKSHEET_NAME, source.REPORTING_YEAR,
        source.REPORTING_WEEK, source.SOURCE_RECORD_COUNT, source.ROW_COUNT,
        source.ERROR_COUNT, source.STATUS, source.NOTES, source.UPLOAD_TIMESTAMP,
        source.CREATED_AT, source.UPDATED_AT
    );

    MERGE INTO EFNS_DEV.CORE.PRODUCTION_RECORD AS target
    USING (
        SELECT
            'DEV_SYNTH_PRODUCTION_' || LPAD(TO_VARCHAR(g.n), 3, '0') AS PRODUCTION_ID,
            'DEV_SYNTH_IMPORT_001' AS IMPORT_ID,
            f.ACCOUNT_ID AS PRODUCER_ACCOUNT_ID,
            'DEV_SYNTH_ACCOUNT_005' AS GRADER_ACCOUNT_ID,
            f.FACILITY_ID,
            f.FLOCK_ID,
            'DEV_SYNTH Fictional Grader' AS GRADER_NAME,
            REPLACE(f.ACCOUNT_ID, 'DEV_SYNTH_ACCOUNT_', 'DEV_SYNTH_PRODUCER_') AS PRODUCER_NUMBER,
            'DEV_SYNTH_GRADER_005' AS GRADER_NUMBER,
            f.FLOCK_NUMBER AS BARN_IDENTITY,
            '2026-W' || LPAD(TO_VARCHAR(MOD(g.n - 1, 52) + 1), 2, '0') AS SOURCE_WEEK_CODE,
            2026 AS REPORTING_YEAR,
            MOD(g.n - 1, 52) + 1 AS REPORTING_WEEK,
            'Conventional' AS MARKETING_TYPE,
            IFF(MOD(g.n, 2) = 0, 'Free Run', 'Conventional') AS HOUSING_SYSTEM,
            'Shell' AS EGG_TYPE,
            f.EGG_COLOUR,
            30 + MOD(g.n, 40) AS FLOCK_AGE,
            1000 + g.n AS NET_WEIGHT,
            66 + MOD(g.n, 5) AS NET_BOXES,
            15 AS NET_PER_BOX,
            20 AS JUMBO,
            100 AS EXTRA_LARGE,
            500 + g.n AS LARGE,
            250 AS MEDIUM,
            75 AS SMALL,
            20 AS PEEWEE,
            10 AS GRADE_B,
            5 AS GRADE_C,
            5 AS CRACKS,
            0 AS NEST_RUN,
            985 + g.n AS SUBTOTAL,
            10 AS REJECTS,
            5 AS LEAKERS,
            1000 + g.n AS TOTAL,
            1000 + g.n AS TOTAL_RECEIVED,
            10 AS REJECTED,
            5 AS LOSS,
            15 AS LEGACY_REJECT_LOSS_TOTAL,
            985 + g.n AS TOTAL_ACCEPTED,
            'SYNTHETIC' AS SOURCE_TYPE,
            NULL AS MATCH_STATUS,
            g.n AS SOURCE_ROW_NUMBER,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS CREATED_AT,
            TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS UPDATED_AT
        FROM (
            SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS n
            FROM TABLE(GENERATOR(ROWCOUNT => 100))
        ) AS g
        JOIN EFNS_DEV.CORE.FLOCK AS f
          ON f.FLOCK_ID = 'DEV_SYNTH_FLOCK_' || LPAD(TO_VARCHAR(MOD(g.n - 1, 12) + 1), 3, '0')
    ) AS source
        ON target.PRODUCTION_ID = source.PRODUCTION_ID
    WHEN NOT MATCHED THEN INSERT (
        PRODUCTION_ID, IMPORT_ID, PRODUCER_ACCOUNT_ID, GRADER_ACCOUNT_ID,
        FACILITY_ID, FLOCK_ID, GRADER_NAME, PRODUCER_NUMBER, GRADER_NUMBER,
        BARN_IDENTITY, SOURCE_WEEK_CODE, REPORTING_YEAR, REPORTING_WEEK,
        MARKETING_TYPE, HOUSING_SYSTEM, EGG_TYPE, EGG_COLOUR, FLOCK_AGE,
        NET_WEIGHT, NET_BOXES, NET_PER_BOX, JUMBO, EXTRA_LARGE, LARGE, MEDIUM,
        SMALL, PEEWEE, GRADE_B, GRADE_C, CRACKS, NEST_RUN, SUBTOTAL, REJECTS,
        LEAKERS, TOTAL, TOTAL_RECEIVED, REJECTED, LOSS,
        LEGACY_REJECT_LOSS_TOTAL, TOTAL_ACCEPTED, SOURCE_TYPE, MATCH_STATUS,
        SOURCE_ROW_NUMBER, CREATED_AT, UPDATED_AT
    ) VALUES (
        source.PRODUCTION_ID, source.IMPORT_ID, source.PRODUCER_ACCOUNT_ID,
        source.GRADER_ACCOUNT_ID, source.FACILITY_ID, source.FLOCK_ID,
        source.GRADER_NAME, source.PRODUCER_NUMBER, source.GRADER_NUMBER,
        source.BARN_IDENTITY, source.SOURCE_WEEK_CODE, source.REPORTING_YEAR,
        source.REPORTING_WEEK, source.MARKETING_TYPE, source.HOUSING_SYSTEM,
        source.EGG_TYPE, source.EGG_COLOUR, source.FLOCK_AGE, source.NET_WEIGHT,
        source.NET_BOXES, source.NET_PER_BOX, source.JUMBO, source.EXTRA_LARGE,
        source.LARGE, source.MEDIUM, source.SMALL, source.PEEWEE,
        source.GRADE_B, source.GRADE_C, source.CRACKS, source.NEST_RUN,
        source.SUBTOTAL, source.REJECTS, source.LEAKERS, source.TOTAL,
        source.TOTAL_RECEIVED, source.REJECTED, source.LOSS,
        source.LEGACY_REJECT_LOSS_TOTAL, source.TOTAL_ACCEPTED,
        source.SOURCE_TYPE, source.MATCH_STATUS, source.SOURCE_ROW_NUMBER,
        source.CREATED_AT, source.UPDATED_AT
    );

    COMMIT;
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;
$$;

-- Verification: each ACTUAL_COUNT must equal EXPECTED_COUNT.
SELECT 'ACCOUNT' AS ENTITY, 5 AS EXPECTED_COUNT, COUNT(*) AS ACTUAL_COUNT
FROM EFNS_DEV.CORE.ACCOUNT WHERE STARTSWITH(ACCOUNT_ID, 'DEV_SYNTH_')
UNION ALL
SELECT 'FACILITY', 8, COUNT(*) FROM EFNS_DEV.CORE.FACILITY WHERE STARTSWITH(FACILITY_ID, 'DEV_SYNTH_')
UNION ALL
SELECT 'FLOCK', 12, COUNT(*) FROM EFNS_DEV.CORE.FLOCK WHERE STARTSWITH(FLOCK_ID, 'DEV_SYNTH_')
UNION ALL
SELECT 'FLOCK_TRANSACTION', 20, COUNT(*) FROM EFNS_DEV.CORE.FLOCK_TRANSACTION WHERE STARTSWITH(FLOCK_TRANSACTION_ID, 'DEV_SYNTH_')
UNION ALL
SELECT 'QUOTA_REGISTRATION', 6, COUNT(*) FROM EFNS_DEV.CORE.QUOTA_REGISTRATION WHERE STARTSWITH(QUOTA_ID, 'DEV_SYNTH_')
UNION ALL
SELECT 'QUOTA_TRANSACTION', 10, COUNT(*) FROM EFNS_DEV.CORE.QUOTA_TRANSACTION WHERE STARTSWITH(QUOTA_TRANSACTION_ID, 'DEV_SYNTH_')
UNION ALL
SELECT 'SALMONELLA_TEST', 10, COUNT(*) FROM EFNS_DEV.CORE.SALMONELLA_TEST WHERE STARTSWITH(SALMONELLA_TEST_ID, 'DEV_SYNTH_')
UNION ALL
SELECT 'IMPORT_BATCH', 1, COUNT(*) FROM EFNS_DEV.RAW.IMPORT_BATCH WHERE STARTSWITH(IMPORT_ID, 'DEV_SYNTH_')
UNION ALL
SELECT 'PRODUCTION_RECORD', 100, COUNT(*) FROM EFNS_DEV.CORE.PRODUCTION_RECORD WHERE STARTSWITH(PRODUCTION_ID, 'DEV_SYNTH_')
UNION ALL
SELECT 'REPORTING.VW_PRODUCTION_SUMMARY', 100, COUNT(*) FROM EFNS_DEV.REPORTING.VW_PRODUCTION_SUMMARY WHERE STARTSWITH(PRODUCTION_ID, 'DEV_SYNTH_')
ORDER BY ENTITY;

-- Verification: each BROKEN_RELATIONSHIP_COUNT must be zero.
SELECT 'FACILITY -> ACCOUNT' AS RELATIONSHIP, COUNT(*) AS BROKEN_RELATIONSHIP_COUNT
FROM EFNS_DEV.CORE.FACILITY child
LEFT JOIN EFNS_DEV.CORE.ACCOUNT parent ON parent.ACCOUNT_ID = child.ACCOUNT_ID
WHERE STARTSWITH(child.FACILITY_ID, 'DEV_SYNTH_') AND parent.ACCOUNT_ID IS NULL
UNION ALL
SELECT 'FLOCK -> ACCOUNT', COUNT(*) FROM EFNS_DEV.CORE.FLOCK child LEFT JOIN EFNS_DEV.CORE.ACCOUNT parent ON parent.ACCOUNT_ID = child.ACCOUNT_ID WHERE STARTSWITH(child.FLOCK_ID, 'DEV_SYNTH_') AND parent.ACCOUNT_ID IS NULL
UNION ALL
SELECT 'FLOCK -> FACILITY', COUNT(*) FROM EFNS_DEV.CORE.FLOCK child LEFT JOIN EFNS_DEV.CORE.FACILITY parent ON parent.FACILITY_ID = child.FACILITY_ID WHERE STARTSWITH(child.FLOCK_ID, 'DEV_SYNTH_') AND parent.FACILITY_ID IS NULL
UNION ALL
SELECT 'FLOCK -> FACILITY_DETAIL', COUNT(*) FROM EFNS_DEV.CORE.FLOCK child LEFT JOIN EFNS_DEV.CORE.FACILITY_DETAIL parent ON parent.FACILITY_DETAIL_ID = child.FACILITY_DETAIL_ID WHERE STARTSWITH(child.FLOCK_ID, 'DEV_SYNTH_') AND child.FACILITY_DETAIL_ID IS NOT NULL AND parent.FACILITY_DETAIL_ID IS NULL
UNION ALL
SELECT 'FLOCK -> QUOTA', COUNT(*) FROM EFNS_DEV.CORE.FLOCK child LEFT JOIN EFNS_DEV.CORE.QUOTA_REGISTRATION parent ON parent.QUOTA_ID = child.QUOTA_ID WHERE STARTSWITH(child.FLOCK_ID, 'DEV_SYNTH_') AND parent.QUOTA_ID IS NULL
UNION ALL
SELECT 'FLOCK_TRANSACTION -> FLOCK', COUNT(*) FROM EFNS_DEV.CORE.FLOCK_TRANSACTION child LEFT JOIN EFNS_DEV.CORE.FLOCK parent ON parent.FLOCK_ID = child.FLOCK_ID WHERE STARTSWITH(child.FLOCK_TRANSACTION_ID, 'DEV_SYNTH_') AND parent.FLOCK_ID IS NULL
UNION ALL
SELECT 'QUOTA_REGISTRATION -> ACCOUNT', COUNT(*) FROM EFNS_DEV.CORE.QUOTA_REGISTRATION child LEFT JOIN EFNS_DEV.CORE.ACCOUNT parent ON parent.ACCOUNT_ID = child.ACCOUNT_ID WHERE STARTSWITH(child.QUOTA_ID, 'DEV_SYNTH_') AND parent.ACCOUNT_ID IS NULL
UNION ALL
SELECT 'QUOTA_TRANSACTION -> QUOTA', COUNT(*) FROM EFNS_DEV.CORE.QUOTA_TRANSACTION child LEFT JOIN EFNS_DEV.CORE.QUOTA_REGISTRATION parent ON parent.QUOTA_ID = child.QUOTA_ID WHERE STARTSWITH(child.QUOTA_TRANSACTION_ID, 'DEV_SYNTH_') AND parent.QUOTA_ID IS NULL
UNION ALL
SELECT 'QUOTA_TRANSACTION -> OWNER_ACCOUNT', COUNT(*) FROM EFNS_DEV.CORE.QUOTA_TRANSACTION child LEFT JOIN EFNS_DEV.CORE.ACCOUNT parent ON parent.ACCOUNT_ID = child.OWNER_ACCOUNT_ID WHERE STARTSWITH(child.QUOTA_TRANSACTION_ID, 'DEV_SYNTH_') AND parent.ACCOUNT_ID IS NULL
UNION ALL
SELECT 'QUOTA_TRANSACTION -> RELATED_ACCOUNT', COUNT(*) FROM EFNS_DEV.CORE.QUOTA_TRANSACTION child LEFT JOIN EFNS_DEV.CORE.ACCOUNT parent ON parent.ACCOUNT_ID = child.RELATED_ACCOUNT_ID WHERE STARTSWITH(child.QUOTA_TRANSACTION_ID, 'DEV_SYNTH_') AND parent.ACCOUNT_ID IS NULL
UNION ALL
SELECT 'QUOTA_TRANSACTION -> RELATED_QUOTA', COUNT(*) FROM EFNS_DEV.CORE.QUOTA_TRANSACTION child LEFT JOIN EFNS_DEV.CORE.QUOTA_REGISTRATION parent ON parent.QUOTA_ID = child.RELATED_QUOTA_ID WHERE STARTSWITH(child.QUOTA_TRANSACTION_ID, 'DEV_SYNTH_') AND child.RELATED_QUOTA_ID IS NOT NULL AND parent.QUOTA_ID IS NULL
UNION ALL
SELECT 'QUOTA_TRANSACTION -> RELATED_TRANSACTION', COUNT(*) FROM EFNS_DEV.CORE.QUOTA_TRANSACTION child LEFT JOIN EFNS_DEV.CORE.QUOTA_TRANSACTION parent ON parent.QUOTA_TRANSACTION_ID = child.RELATED_TRANSACTION_ID WHERE STARTSWITH(child.QUOTA_TRANSACTION_ID, 'DEV_SYNTH_') AND child.RELATED_TRANSACTION_ID IS NOT NULL AND parent.QUOTA_TRANSACTION_ID IS NULL
UNION ALL
SELECT 'SALMONELLA_TEST -> FLOCK', COUNT(*) FROM EFNS_DEV.CORE.SALMONELLA_TEST child LEFT JOIN EFNS_DEV.CORE.FLOCK parent ON parent.FLOCK_ID = child.FLOCK_ID WHERE STARTSWITH(child.SALMONELLA_TEST_ID, 'DEV_SYNTH_') AND parent.FLOCK_ID IS NULL
UNION ALL
SELECT 'SALMONELLA_TEST -> ACCOUNT', COUNT(*) FROM EFNS_DEV.CORE.SALMONELLA_TEST child LEFT JOIN EFNS_DEV.CORE.ACCOUNT parent ON parent.ACCOUNT_ID = child.ACCOUNT_ID WHERE STARTSWITH(child.SALMONELLA_TEST_ID, 'DEV_SYNTH_') AND parent.ACCOUNT_ID IS NULL
UNION ALL
SELECT 'PRODUCTION_RECORD -> IMPORT_BATCH', COUNT(*) FROM EFNS_DEV.CORE.PRODUCTION_RECORD child LEFT JOIN EFNS_DEV.RAW.IMPORT_BATCH parent ON parent.IMPORT_ID = child.IMPORT_ID WHERE STARTSWITH(child.PRODUCTION_ID, 'DEV_SYNTH_') AND parent.IMPORT_ID IS NULL
UNION ALL
SELECT 'PRODUCTION_RECORD -> ACCOUNT', COUNT(*) FROM EFNS_DEV.CORE.PRODUCTION_RECORD child LEFT JOIN EFNS_DEV.CORE.ACCOUNT parent ON parent.ACCOUNT_ID = child.PRODUCER_ACCOUNT_ID WHERE STARTSWITH(child.PRODUCTION_ID, 'DEV_SYNTH_') AND parent.ACCOUNT_ID IS NULL
UNION ALL
SELECT 'PRODUCTION_RECORD -> GRADER_ACCOUNT', COUNT(*) FROM EFNS_DEV.CORE.PRODUCTION_RECORD child LEFT JOIN EFNS_DEV.CORE.ACCOUNT parent ON parent.ACCOUNT_ID = child.GRADER_ACCOUNT_ID WHERE STARTSWITH(child.PRODUCTION_ID, 'DEV_SYNTH_') AND child.GRADER_ACCOUNT_ID IS NOT NULL AND parent.ACCOUNT_ID IS NULL
UNION ALL
SELECT 'PRODUCTION_RECORD -> FACILITY', COUNT(*) FROM EFNS_DEV.CORE.PRODUCTION_RECORD child LEFT JOIN EFNS_DEV.CORE.FACILITY parent ON parent.FACILITY_ID = child.FACILITY_ID WHERE STARTSWITH(child.PRODUCTION_ID, 'DEV_SYNTH_') AND parent.FACILITY_ID IS NULL
UNION ALL
SELECT 'PRODUCTION_RECORD -> FLOCK', COUNT(*) FROM EFNS_DEV.CORE.PRODUCTION_RECORD child LEFT JOIN EFNS_DEV.CORE.FLOCK parent ON parent.FLOCK_ID = child.FLOCK_ID WHERE STARTSWITH(child.PRODUCTION_ID, 'DEV_SYNTH_') AND parent.FLOCK_ID IS NULL
ORDER BY RELATIONSHIP;

-- Repository-level semantic checks not represented by every physical FK.
SELECT
    (
        SELECT COUNT(*) FROM EFNS_DEV.CORE.FLOCK fl
        JOIN EFNS_DEV.CORE.FACILITY fa ON fa.FACILITY_ID = fl.FACILITY_ID
        WHERE STARTSWITH(fl.FLOCK_ID, 'DEV_SYNTH_') AND fa.ACCOUNT_ID <> fl.ACCOUNT_ID
    ) AS FLOCK_FACILITY_ACCOUNT_MISMATCH_COUNT,
    (
        SELECT COUNT(*) FROM EFNS_DEV.CORE.FLOCK fl
        JOIN EFNS_DEV.CORE.QUOTA_REGISTRATION qr ON qr.QUOTA_ID = fl.QUOTA_ID
        WHERE STARTSWITH(fl.FLOCK_ID, 'DEV_SYNTH_') AND qr.ACCOUNT_ID <> fl.ACCOUNT_ID
    ) AS FLOCK_QUOTA_ACCOUNT_MISMATCH_COUNT,
    (
        SELECT COUNT(*) FROM EFNS_DEV.CORE.QUOTA_TRANSACTION qt
        JOIN EFNS_DEV.CORE.QUOTA_REGISTRATION qr ON qr.QUOTA_ID = qt.QUOTA_ID
        WHERE STARTSWITH(qt.QUOTA_TRANSACTION_ID, 'DEV_SYNTH_')
          AND qr.ACCOUNT_ID <> qt.OWNER_ACCOUNT_ID
    ) AS QUOTA_OWNER_MISMATCH_COUNT,
    (
        SELECT COUNT(*) FROM EFNS_DEV.CORE.SALMONELLA_TEST st
        JOIN EFNS_DEV.CORE.FLOCK fl ON fl.FLOCK_ID = st.FLOCK_ID
        WHERE STARTSWITH(st.SALMONELLA_TEST_ID, 'DEV_SYNTH_')
          AND fl.ACCOUNT_ID <> st.ACCOUNT_ID
    ) AS SALMONELLA_ACCOUNT_MISMATCH_COUNT,
    (
        SELECT COUNT(*) FROM EFNS_DEV.CORE.SALMONELLA_TEST st
        JOIN EFNS_DEV.CORE.FLOCK fl ON fl.FLOCK_ID = st.FLOCK_ID
        WHERE STARTSWITH(st.SALMONELLA_TEST_ID, 'DEV_SYNTH_')
          AND fl.PERMIT_NUMBER <> st.PERMIT_NUMBER
    ) AS SALMONELLA_PERMIT_MISMATCH_COUNT,
    (
        SELECT COUNT(*) FROM EFNS_DEV.CORE.PRODUCTION_RECORD pr
        JOIN EFNS_DEV.CORE.FLOCK fl ON fl.FLOCK_ID = pr.FLOCK_ID
        WHERE STARTSWITH(pr.PRODUCTION_ID, 'DEV_SYNTH_')
          AND (pr.PRODUCER_ACCOUNT_ID <> fl.ACCOUNT_ID OR pr.FACILITY_ID <> fl.FACILITY_ID)
    ) AS PRODUCTION_FLOCK_CONTEXT_MISMATCH_COUNT;
