-- EFNS DEV ONLY - TARGETED DEV_SYNTH CLEANUP
-- Removes only records owned by sql/09_dev_synthetic_seed.sql or additional
-- records deliberately created with the DEV_SYNTH identifier prefix.
-- No schema, security object, application user, or audit event is modified.

USE ROLE SYSADMIN;
USE WAREHOUSE EFNS_DEV_WH;
USE DATABASE EFNS_DEV;

EXECUTE IMMEDIATE $$
BEGIN
    BEGIN TRANSACTION;

    -- Deepest production and import dependencies first.
    DELETE FROM EFNS_DEV.CORE.PRODUCTION_SIZE_BREAKDOWN
    WHERE STARTSWITH(PRODUCTION_ID, 'DEV_SYNTH_');

    DELETE FROM EFNS_DEV.CORE.PRODUCTION_RECORD
    WHERE STARTSWITH(PRODUCTION_ID, 'DEV_SYNTH_');

    DELETE FROM EFNS_DEV.RAW.IMPORT_RAW_ROW
    WHERE STARTSWITH(IMPORT_ID, 'DEV_SYNTH_');

    DELETE FROM EFNS_DEV.RAW.IMPORT_BATCH
    WHERE STARTSWITH(IMPORT_ID, 'DEV_SYNTH_');

    -- Operational children before parents.
    DELETE FROM EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE
    WHERE STARTSWITH(SALMONELLA_TEST_ID, 'DEV_SYNTH_');

    DELETE FROM EFNS_DEV.CORE.SALMONELLA_TEST
    WHERE STARTSWITH(SALMONELLA_TEST_ID, 'DEV_SYNTH_');

    DELETE FROM EFNS_DEV.CORE.FLOCK_TRANSACTION
    WHERE STARTSWITH(FLOCK_TRANSACTION_ID, 'DEV_SYNTH_');

    DELETE FROM EFNS_DEV.CORE.QUOTA_TRANSACTION
    WHERE STARTSWITH(QUOTA_TRANSACTION_ID, 'DEV_SYNTH_');

    DELETE FROM EFNS_DEV.CORE.FLOCK
    WHERE STARTSWITH(FLOCK_ID, 'DEV_SYNTH_');

    DELETE FROM EFNS_DEV.CORE.FACILITY_DETAIL
    WHERE STARTSWITH(FACILITY_ID, 'DEV_SYNTH_');

    DELETE FROM EFNS_DEV.CORE.QUOTA_REGISTRATION
    WHERE STARTSWITH(QUOTA_ID, 'DEV_SYNTH_');

    DELETE FROM EFNS_DEV.CORE.FACILITY
    WHERE STARTSWITH(FACILITY_ID, 'DEV_SYNTH_');

    DELETE FROM EFNS_DEV.CORE.ACCOUNT
    WHERE STARTSWITH(ACCOUNT_ID, 'DEV_SYNTH_');

    COMMIT;
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;
$$;

-- Verification: every count must be zero.
SELECT 'ACCOUNT' AS ENTITY, COUNT(*) AS REMAINING_DEV_SYNTH_ROWS FROM EFNS_DEV.CORE.ACCOUNT WHERE STARTSWITH(ACCOUNT_ID, 'DEV_SYNTH_')
UNION ALL SELECT 'FACILITY', COUNT(*) FROM EFNS_DEV.CORE.FACILITY WHERE STARTSWITH(FACILITY_ID, 'DEV_SYNTH_')
UNION ALL SELECT 'FACILITY_DETAIL', COUNT(*) FROM EFNS_DEV.CORE.FACILITY_DETAIL WHERE STARTSWITH(FACILITY_ID, 'DEV_SYNTH_')
UNION ALL SELECT 'FLOCK', COUNT(*) FROM EFNS_DEV.CORE.FLOCK WHERE STARTSWITH(FLOCK_ID, 'DEV_SYNTH_')
UNION ALL SELECT 'FLOCK_TRANSACTION', COUNT(*) FROM EFNS_DEV.CORE.FLOCK_TRANSACTION WHERE STARTSWITH(FLOCK_TRANSACTION_ID, 'DEV_SYNTH_')
UNION ALL SELECT 'QUOTA_REGISTRATION', COUNT(*) FROM EFNS_DEV.CORE.QUOTA_REGISTRATION WHERE STARTSWITH(QUOTA_ID, 'DEV_SYNTH_')
UNION ALL SELECT 'QUOTA_TRANSACTION', COUNT(*) FROM EFNS_DEV.CORE.QUOTA_TRANSACTION WHERE STARTSWITH(QUOTA_TRANSACTION_ID, 'DEV_SYNTH_')
UNION ALL SELECT 'SALMONELLA_TEST', COUNT(*) FROM EFNS_DEV.CORE.SALMONELLA_TEST WHERE STARTSWITH(SALMONELLA_TEST_ID, 'DEV_SYNTH_')
UNION ALL SELECT 'SALMONELLA_TEST_SAMPLE', COUNT(*) FROM EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE WHERE STARTSWITH(SALMONELLA_TEST_ID, 'DEV_SYNTH_')
UNION ALL SELECT 'IMPORT_BATCH', COUNT(*) FROM EFNS_DEV.RAW.IMPORT_BATCH WHERE STARTSWITH(IMPORT_ID, 'DEV_SYNTH_')
UNION ALL SELECT 'IMPORT_RAW_ROW', COUNT(*) FROM EFNS_DEV.RAW.IMPORT_RAW_ROW WHERE STARTSWITH(IMPORT_ID, 'DEV_SYNTH_')
UNION ALL SELECT 'PRODUCTION_RECORD', COUNT(*) FROM EFNS_DEV.CORE.PRODUCTION_RECORD WHERE STARTSWITH(PRODUCTION_ID, 'DEV_SYNTH_')
UNION ALL SELECT 'PRODUCTION_SIZE_BREAKDOWN', COUNT(*) FROM EFNS_DEV.CORE.PRODUCTION_SIZE_BREAKDOWN WHERE STARTSWITH(PRODUCTION_ID, 'DEV_SYNTH_')
ORDER BY ENTITY;
