-- EFNS EIMS v3 / DEV-only additive deployment.
-- This script changes schema metadata only. It does not load EIMS source rows.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EFNS_DEV_WH;
USE DATABASE EFNS_DEV;

-- ============================================================
-- 1. Preflight and environment guard
-- ============================================================

SELECT
    CURRENT_ROLE() AS CURRENT_ROLE,
    CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
    CURRENT_DATABASE() AS CURRENT_DATABASE,
    CURRENT_SCHEMA() AS CURRENT_SCHEMA;

EXECUTE IMMEDIATE $$
DECLARE
    WRONG_DATABASE EXCEPTION (-20001, 'EIMS v3 deployment stopped: current database must be EFNS_DEV.');
BEGIN
    IF (CURRENT_DATABASE() IS NULL OR UPPER(CURRENT_DATABASE()) <> 'EFNS_DEV') THEN
        RAISE WRONG_DATABASE;
    END IF;
END;
$$;

CREATE SCHEMA IF NOT EXISTS EFNS_DEV.RAW COMMENT = 'Source-preserving import and migration records';
CREATE SCHEMA IF NOT EXISTS EFNS_DEV.CORE COMMENT = 'EFNS operational entities';
CREATE ROLE IF NOT EXISTS EFNS_DEV_APP_OWNER
    COMMENT = 'Owns the EFNS DEV Streamlit app and runtime objects';

-- ============================================================
-- 2. Existing parent and business tables
-- ============================================================

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.ACCOUNT (
    ACCOUNT_ID VARCHAR(36) NOT NULL,
    REGISTRATION_NUMBER VARCHAR(64),
    ORGANIZATION_NAME VARCHAR(255) NOT NULL,
    ADDRESS_LINE1 VARCHAR(255), ADDRESS_LINE2 VARCHAR(255), ADDRESS_LINE3 VARCHAR(255),
    CITY VARCHAR(100), PROVINCE VARCHAR(50), POSTAL_CODE VARCHAR(20), COUNTRY_REGION VARCHAR(100),
    LATITUDE NUMBER(10,7), LONGITUDE NUMBER(10,7),
    CONTACT_NAME VARCHAR(255), CONTACT_PHONE VARCHAR(50), CONTACT_EMAIL VARCHAR(255),
    FAX VARCHAR(50), WEBSITE VARCHAR(500), LICENCE_NUMBER VARCHAR(64),
    PARENT_ACCOUNT_ID VARCHAR(36), GRADING_STATION_ACCOUNT_ID VARCHAR(36), PULLET_GROWER_ACCOUNT_ID VARCHAR(36),
    PROVINCE_OF_REGISTRATION VARCHAR(50), SPENT_FOWL_PLANS VARCHAR(2000),
    DEFAULT_ON_REPORTS BOOLEAN DEFAULT FALSE, NO_SVG BOOLEAN DEFAULT FALSE, DESCRIPTION VARCHAR(4000),
    PRODUCER_ROLE BOOLEAN DEFAULT FALSE, BREEDER_ROLE BOOLEAN DEFAULT FALSE,
    HATCHERY_ROLE BOOLEAN DEFAULT FALSE, PULLET_GROWER_ROLE BOOLEAN DEFAULT FALSE,
    GRADER_ROLE BOOLEAN DEFAULT FALSE, PROCESSOR_BREAKER_ROLE BOOLEAN DEFAULT FALSE,
    DISPOSAL_PLANT_ROLE BOOLEAN DEFAULT FALSE, UNREGULATED_ROLE BOOLEAN DEFAULT FALSE,
    PROV_BOARD_EFC_ROLE BOOLEAN DEFAULT FALSE, GOVERNMENT_ROLE BOOLEAN DEFAULT FALSE,
    VENDOR_ROLE BOOLEAN DEFAULT FALSE, RESEARCH_EXEMPT_ROLE BOOLEAN DEFAULT FALSE,
    SHIPPER_ROLE BOOLEAN DEFAULT FALSE, OTHER_ROLE BOOLEAN DEFAULT FALSE,
    STATUS VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT FK_ACCOUNT_PARENT FOREIGN KEY (PARENT_ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_ACCOUNT_GRADING_STATION FOREIGN KEY (GRADING_STATION_ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_ACCOUNT_PULLET_GROWER FOREIGN KEY (PULLET_GROWER_ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.CONTACT (
    CONTACT_ID VARCHAR(36) NOT NULL,
    ACCOUNT_ID VARCHAR(36),
    FULL_NAME VARCHAR(500) NOT NULL,
    FIRST_NAME VARCHAR(255), MIDDLE_NAME VARCHAR(255), LAST_NAME VARCHAR(255),
    JOB_TITLE VARCHAR(255), EMAIL VARCHAR(500), PHONE VARCHAR(100), MOBILE_PHONE VARCHAR(100), FAX VARCHAR(100),
    ADDRESS_LINE1 VARCHAR(500), ADDRESS_LINE2 VARCHAR(500), CITY VARCHAR(255), PROVINCE VARCHAR(100),
    POSTAL_CODE VARCHAR(50), COUNTRY_REGION VARCHAR(100), EIMS_CONTACT_NUMBER VARCHAR(100),
    LANGUAGE_PREFERENCE VARCHAR(100), PRIME_CONTACT BOOLEAN, STATUS VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_CONTACT PRIMARY KEY (CONTACT_ID),
    CONSTRAINT FK_CONTACT_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.FARM_LOCATION (
    FARM_LOCATION_ID VARCHAR(36) NOT NULL,
    ACCOUNT_ID VARCHAR(36) NOT NULL,
    LOCATION_NAME VARCHAR(255) NOT NULL,
    ADDRESS_1 VARCHAR(255), ADDRESS_2 VARCHAR(255), CITY VARCHAR(100), PROVINCE VARCHAR(50),
    POSTAL_CODE VARCHAR(20), PHONE VARCHAR(50), FAX VARCHAR(100), EIMS_LOCATION_ID VARCHAR(100), STATUS VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_FARM_LOCATION PRIMARY KEY (FARM_LOCATION_ID),
    CONSTRAINT FK_FARM_LOCATION_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.FACILITY (
    FACILITY_ID VARCHAR(36) NOT NULL,
    ACCOUNT_ID VARCHAR(36) NOT NULL,
    FARM_LOCATION_ID VARCHAR(36),
    FACILITY_NAME VARCHAR(255) NOT NULL,
    FACILITY_TYPE VARCHAR(100), HOUSING_SYSTEM VARCHAR(100), STATUS VARCHAR(100),
    ACTIVATION_DATE DATE, CONSTRUCTION_DATE DATE, RENOVATION_DATE DATE,
    CLOSURE_DATE DATE, DESTRUCTION_DATE DATE, INACTIVE_DATE DATE,
    FACILITY_QUOTA NUMBER(18,4), MANURE_DISPOSAL VARCHAR(100), COMMENTS VARCHAR(4000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_FACILITY PRIMARY KEY (FACILITY_ID),
    CONSTRAINT FK_FACILITY_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_FACILITY_FARM_LOCATION FOREIGN KEY (FARM_LOCATION_ID) REFERENCES EFNS_DEV.CORE.FARM_LOCATION (FARM_LOCATION_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.FACILITY_DETAIL (
    FACILITY_DETAIL_ID VARCHAR(36) NOT NULL,
    FACILITY_ID VARCHAR(36) NOT NULL,
    DETAIL_NAME VARCHAR(255), DETAIL_TYPE VARCHAR(100), STATUS VARCHAR(100), COMMENTS VARCHAR(4000),
    EIMS_FACILITY_DETAIL_ID VARCHAR(100), BIRD_COLOUR VARCHAR(100), BIRDS_HOUSED NUMBER(18,0),
    CAGE_BRAND VARCHAR(255), DATE_INSTALLED DATE, HEIGHT NUMBER(18,4),
    HIGHEST_BIRDS_PER_CAGE NUMBER(18,4), LENGTH NUMBER(18,4), NUMBER_OF_CAGES NUMBER(18,0),
    SQUARE_INCHES NUMBER(18,4), WIDTH NUMBER(18,4),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_FACILITY_DETAIL PRIMARY KEY (FACILITY_DETAIL_ID),
    CONSTRAINT FK_FACILITY_DETAIL_FACILITY FOREIGN KEY (FACILITY_ID) REFERENCES EFNS_DEV.CORE.FACILITY (FACILITY_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.QUOTA_REGISTRATION (
    QUOTA_ID VARCHAR(36) NOT NULL,
    REGISTRATION_NUMBER VARCHAR(64) NOT NULL,
    ACCOUNT_ID VARCHAR(36) NOT NULL,
    QUOTA_NAME VARCHAR(255), QUOTA_TYPE VARCHAR(100) NOT NULL, STATUS VARCHAR(100),
    EFFECTIVE_DATE DATE, END_DATE DATE, COMMENTS VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_QUOTA_REGISTRATION PRIMARY KEY (QUOTA_ID),
    CONSTRAINT FK_QUOTA_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.FLOCK (
    FLOCK_ID VARCHAR(36) NOT NULL,
    FLOCK_NUMBER VARCHAR(64) NOT NULL,
    ACCOUNT_ID VARCHAR(36) NOT NULL,
    FACILITY_ID VARCHAR(36), FACILITY_DETAIL_ID VARCHAR(36), QUOTA_ID VARCHAR(36),
    FLOCK_QUOTA_TYPE VARCHAR(100), STATUS VARCHAR(100), CREATE_DELIVERY_TRANSACTION BOOLEAN,
    PERMIT_NUMBER VARCHAR(100) NOT NULL, PERMIT_DATE DATE, HATCH_DATE DATE NOT NULL, DATE_ORDERED DATE,
    BIRD_COUNT NUMBER(12,0) NOT NULL, EGG_COLOUR VARCHAR(50), BIRD_STRAIN VARCHAR(100),
    PLACEMENT_DATE DATE, EST_DISPOSAL DATE, DISPOSAL_DATE DATE, BIRDS_DISPOSED NUMBER(12,0),
    BREEDER VARCHAR(255), HATCHERY VARCHAR(255), PULLET_GROWER VARCHAR(255),
    DISPOSAL_PLANT VARCHAR(255), DISPOSAL_METHOD VARCHAR(100), COMMENTS VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_FLOCK PRIMARY KEY (FLOCK_ID),
    CONSTRAINT FK_FLOCK_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_FLOCK_FACILITY FOREIGN KEY (FACILITY_ID) REFERENCES EFNS_DEV.CORE.FACILITY (FACILITY_ID),
    CONSTRAINT FK_FLOCK_DETAIL FOREIGN KEY (FACILITY_DETAIL_ID) REFERENCES EFNS_DEV.CORE.FACILITY_DETAIL (FACILITY_DETAIL_ID),
    CONSTRAINT FK_FLOCK_QUOTA FOREIGN KEY (QUOTA_ID) REFERENCES EFNS_DEV.CORE.QUOTA_REGISTRATION (QUOTA_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.FLOCK_TRANSACTION (
    FLOCK_TRANSACTION_ID VARCHAR(36) NOT NULL,
    FLOCK_ID VARCHAR(36) NOT NULL,
    TRANSACTION_TYPE VARCHAR(100) NOT NULL,
    QUANTITY NUMBER(12,2) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_FLOCK_TRANSACTION PRIMARY KEY (FLOCK_TRANSACTION_ID),
    CONSTRAINT FK_FLOCK_TRANSACTION_FLOCK FOREIGN KEY (FLOCK_ID) REFERENCES EFNS_DEV.CORE.FLOCK (FLOCK_ID),
    CONSTRAINT CK_FLOCK_TRANSACTION_QUANTITY CHECK (QUANTITY >= 0)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION (
    QUOTA_TRANSACTION_ID VARCHAR(36) NOT NULL,
    TRANSACTION_TYPE VARCHAR(100) NOT NULL,
    QUOTA_ID VARCHAR(36) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL, END_DATE DATE,
    QUOTA_COUNT NUMBER(18,4) NOT NULL,
    OWNER_ACCOUNT_ID VARCHAR(36) NOT NULL, RELATED_ACCOUNT_ID VARCHAR(36),
    RELATED_QUOTA_ID VARCHAR(36), RELATED_TRANSACTION_ID VARCHAR(36),
    PRICE NUMBER(18,4), QUOTA_LEASE_TYPE VARCHAR(100), COMMENTS VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_QUOTA_TRANSACTION PRIMARY KEY (QUOTA_TRANSACTION_ID),
    CONSTRAINT FK_QUOTA_TRANSACTION_QUOTA FOREIGN KEY (QUOTA_ID) REFERENCES EFNS_DEV.CORE.QUOTA_REGISTRATION (QUOTA_ID),
    CONSTRAINT FK_QUOTA_TRANSACTION_OWNER FOREIGN KEY (OWNER_ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_QUOTA_TRANSACTION_RELATED_ACCOUNT FOREIGN KEY (RELATED_ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_QUOTA_TRANSACTION_RELATED_QUOTA FOREIGN KEY (RELATED_QUOTA_ID) REFERENCES EFNS_DEV.CORE.QUOTA_REGISTRATION (QUOTA_ID),
    CONSTRAINT FK_QUOTA_TRANSACTION_RELATED_TRANSACTION FOREIGN KEY (RELATED_TRANSACTION_ID) REFERENCES EFNS_DEV.CORE.QUOTA_TRANSACTION (QUOTA_TRANSACTION_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.SALMONELLA_TEST (
    SALMONELLA_TEST_ID VARCHAR(36) NOT NULL,
    FLOCK_ID VARCHAR(36) NOT NULL, ACCOUNT_ID VARCHAR(36) NOT NULL,
    PERMIT_NUMBER VARCHAR(100) NOT NULL, TESTING_DATE DATE NOT NULL,
    INSPECTOR VARCHAR(255), NUMBER_OF_SAMPLES NUMBER(10,0), TEST_RESULT VARCHAR(100), TEST_TYPE VARCHAR(100),
    DATE_RESULT_SENT DATE, DATE_RECEIVED DATE, CASE_FILE_NUMBER VARCHAR(100),
    INVOICE_NUMBER VARCHAR(100), INVOICE_DATE DATE, COMMENTS VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_SALMONELLA_TEST PRIMARY KEY (SALMONELLA_TEST_ID),
    CONSTRAINT FK_SALMONELLA_TEST_FLOCK FOREIGN KEY (FLOCK_ID) REFERENCES EFNS_DEV.CORE.FLOCK (FLOCK_ID),
    CONSTRAINT FK_SALMONELLA_TEST_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE (
    SALMONELLA_TEST_SAMPLE_ID VARCHAR(36) NOT NULL,
    SALMONELLA_TEST_ID VARCHAR(36) NOT NULL,
    SAMPLE_REFERENCE VARCHAR(100), TEST_AREA VARCHAR(255), SEROTYPE VARCHAR(255), PHAGE VARCHAR(255),
    STATUS VARCHAR(100), COMMENTS VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_SALMONELLA_TEST_SAMPLE PRIMARY KEY (SALMONELLA_TEST_SAMPLE_ID),
    CONSTRAINT FK_SALMONELLA_SAMPLE_TEST FOREIGN KEY (SALMONELLA_TEST_ID) REFERENCES EFNS_DEV.CORE.SALMONELLA_TEST (SALMONELLA_TEST_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.QUOTA_ALLOCATION (
    QUOTA_ALLOCATION_ID VARCHAR(36) NOT NULL,
    ALLOCATION_COUNT NUMBER(18,4) NOT NULL,
    COMMENTS VARCHAR(4000), EFFECTIVE_DATE DATE NOT NULL, EIMS_ALLOCATION_ID VARCHAR(100),
    PROVINCE VARCHAR(100), QUOTA_TYPE VARCHAR(100) NOT NULL, STATUS VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_QUOTA_ALLOCATION PRIMARY KEY (QUOTA_ALLOCATION_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.DIM_EFC_DATE (
    DAY DATE NOT NULL,
    EFC_YEAR NUMBER(4,0), EFC_WEEK_NUMBER NUMBER(2,0), EFC_WEEK VARCHAR(50),
    EFC_WEEK_LABEL VARCHAR(100), EFC_LONG_NAME VARCHAR(255), EFC_PERIOD NUMBER(4,0),
    EFC_PERIOD_ALIAS VARCHAR(100), EFC_QUARTER NUMBER(2,0),
    ELEMENT_CODE VARCHAR(100), ELEMENT_CODES VARCHAR(16000), PREVIOUS_QUARTER VARCHAR(100),
    PREV_YEAR NUMBER(4,0), PREV_WEEK NUMBER(4,0), PREV_QUARTER NUMBER(4,0), DATE_VALUE DATE,
    MONTH_NUMBER NUMBER(2,0), MONTH_TEXT VARCHAR(20), DAYS_IN_MONTH NUMBER(2,0),
    YEAR_NUMBER NUMBER(4,0), YEAR_MONTH VARCHAR(20), QUARTER_NUMBER NUMBER(2,0),
    DAYS_IN_QUARTER NUMBER(3,0), YEAR_QUARTER VARCHAR(20), DAY_STRING VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_DIM_EFC_DATE PRIMARY KEY (DAY)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.IMPORT_BATCH (
    IMPORT_ID VARCHAR(64) NOT NULL,
    FILENAME VARCHAR(500) NOT NULL,
    SOURCE VARCHAR(255), FILE_HASH VARCHAR(64), FILE_SIZE_BYTES NUMBER(18,0),
    WORKSHEET_NAME VARCHAR(255), REPORTING_YEAR NUMBER(4,0), REPORTING_WEEK NUMBER(2,0),
    SOURCE_RECORD_COUNT NUMBER(18,0), ROW_COUNT NUMBER(18,0), ERROR_COUNT NUMBER(18,0),
    STATUS VARCHAR(50), NOTES VARCHAR(2000),
    UPLOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_IMPORT_BATCH PRIMARY KEY (IMPORT_ID),
    CONSTRAINT UQ_IMPORT_BATCH_HASH UNIQUE (FILE_HASH)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD (
    PRODUCTION_ID VARCHAR(36) NOT NULL,
    IMPORT_ID VARCHAR(64) NOT NULL,
    PRODUCER_ACCOUNT_ID VARCHAR(36), GRADER_ACCOUNT_ID VARCHAR(36), FACILITY_ID VARCHAR(36), FLOCK_ID VARCHAR(36),
    GRADER_NAME VARCHAR(255), PRODUCER_NUMBER VARCHAR(100), GRADER_NUMBER VARCHAR(100), BARN_IDENTITY VARCHAR(100),
    SOURCE_WEEK_CODE VARCHAR(20), REPORTING_YEAR NUMBER(4,0), REPORTING_WEEK NUMBER(2,0),
    MARKETING_TYPE VARCHAR(100), HOUSING_SYSTEM VARCHAR(100), EGG_TYPE VARCHAR(100), EGG_COLOUR VARCHAR(50),
    FLOCK_AGE NUMBER(10,0), NET_WEIGHT NUMBER(18,4), NET_BOXES NUMBER(18,4), NET_PER_BOX NUMBER(18,4),
    JUMBO NUMBER(18,4), EXTRA_LARGE NUMBER(18,4), LARGE NUMBER(18,4), MEDIUM NUMBER(18,4),
    SMALL NUMBER(18,4), PEEWEE NUMBER(18,4), GRADE_B NUMBER(18,4), GRADE_C NUMBER(18,4),
    CRACKS NUMBER(18,4), NEST_RUN NUMBER(18,4), NEST_RUN_25_PLUS NUMBER(18,4),
    NEST_RUN_24_PLUS NUMBER(18,4), NEST_RUN_23_PLUS NUMBER(18,4), NEST_RUN_22_PLUS NUMBER(18,4),
    NEST_RUN_21_PLUS NUMBER(18,4), NEST_RUN_20_PLUS NUMBER(18,4), NEST_RUN_19_PLUS NUMBER(18,4),
    NEST_RUN_18_PLUS NUMBER(18,4), NEST_RUN_17_PLUS NUMBER(18,4),
    OTHER_LEVIABLE NUMBER(18,4), OTHER_NON_LEVIABLE NUMBER(18,4),
    FARM_GATE_SALES NUMBER(18,4), ON_FARM_CONSUMPTION NUMBER(18,4), SUBTOTAL NUMBER(18,4),
    REJECTS NUMBER(18,4), LEAKERS NUMBER(18,4), TOTAL NUMBER(18,4),
    TOTAL_RECEIVED NUMBER(18,4), REJECTED NUMBER(18,4), LOSS NUMBER(18,4),
    LEGACY_REJECT_LOSS_TOTAL NUMBER(18,4), TOTAL_ACCEPTED NUMBER(18,4),
    SOURCE_TYPE VARCHAR(50) NOT NULL, MATCH_STATUS VARCHAR(50), SOURCE_ROW_NUMBER NUMBER(18,0),
    MATCH_CONFIRMED_AT TIMESTAMP_NTZ, MATCH_CONFIRMED_BY VARCHAR(255),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_PRODUCTION_RECORD PRIMARY KEY (PRODUCTION_ID),
    CONSTRAINT FK_PRODUCTION_IMPORT FOREIGN KEY (IMPORT_ID) REFERENCES EFNS_DEV.RAW.IMPORT_BATCH (IMPORT_ID),
    CONSTRAINT FK_PRODUCTION_ACCOUNT FOREIGN KEY (PRODUCER_ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_PRODUCTION_GRADER_ACCOUNT FOREIGN KEY (GRADER_ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID),
    CONSTRAINT FK_PRODUCTION_FACILITY FOREIGN KEY (FACILITY_ID) REFERENCES EFNS_DEV.CORE.FACILITY (FACILITY_ID),
    CONSTRAINT FK_PRODUCTION_FLOCK FOREIGN KEY (FLOCK_ID) REFERENCES EFNS_DEV.CORE.FLOCK (FLOCK_ID)
);

-- ============================================================
-- 3. RAW migration infrastructure and full source lineage
-- ============================================================

CREATE STAGE IF NOT EXISTS EFNS_DEV.RAW.EIMS_MIGRATION_FILES
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Encrypted EIMS migration packages for EFNS DEV';

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.MIGRATION_BATCH (
    MIGRATION_BATCH_ID VARCHAR(64) NOT NULL,
    PACKAGE_HASH VARCHAR(64) NOT NULL,
    SCHEMA_VERSION VARCHAR(100) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    SOURCE_FILE_COUNT NUMBER(10,0) NOT NULL,
    SOURCE_ROW_COUNT NUMBER(18,0) NOT NULL,
    READY_ROW_COUNT NUMBER(18,0) NOT NULL,
    REJECTED_ROW_COUNT NUMBER(18,0) NOT NULL,
    CREATED_BY VARCHAR(255), COMMITTED_AT TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_MIGRATION_BATCH PRIMARY KEY (MIGRATION_BATCH_ID),
    CONSTRAINT UQ_MIGRATION_BATCH_HASH UNIQUE (PACKAGE_HASH)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.MIGRATION_FILE (
    MIGRATION_FILE_ID VARCHAR(36) NOT NULL,
    MIGRATION_BATCH_ID VARCHAR(64) NOT NULL,
    SOURCE_FILENAME VARCHAR(500) NOT NULL,
    SOURCE_ENTITY VARCHAR(100) NOT NULL,
    FILE_HASH VARCHAR(64) NOT NULL,
    FILE_SIZE_BYTES NUMBER(18,0), SOURCE_ROW_COUNT NUMBER(18,0), STAGE_PATH VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_MIGRATION_FILE PRIMARY KEY (MIGRATION_FILE_ID),
    CONSTRAINT FK_MIGRATION_FILE_BATCH FOREIGN KEY (MIGRATION_BATCH_ID) REFERENCES EFNS_DEV.RAW.MIGRATION_BATCH (MIGRATION_BATCH_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW (
    MIGRATION_RAW_ROW_ID VARCHAR(64) NOT NULL,
    MIGRATION_BATCH_ID VARCHAR(64) NOT NULL,
    SOURCE_FILENAME VARCHAR(500) NOT NULL,
    SOURCE_ENTITY VARCHAR(100) NOT NULL,
    SOURCE_ROW_NUMBER NUMBER(18,0) NOT NULL,
    SOURCE_ID VARCHAR(255), TARGET_ID VARCHAR(255),
    RAW_DATA VARIANT NOT NULL,
    NORMALIZED_DATA VARIANT,
    VALIDATION_STATUS VARCHAR(30) NOT NULL,
    MATCH_STATUS VARCHAR(30), VALIDATION_MESSAGES VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_MIGRATION_RAW_ROW PRIMARY KEY (MIGRATION_RAW_ROW_ID),
    CONSTRAINT FK_MIGRATION_RAW_ROW_BATCH FOREIGN KEY (MIGRATION_BATCH_ID) REFERENCES EFNS_DEV.RAW.MIGRATION_BATCH (MIGRATION_BATCH_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.MIGRATION_ID_MAP (
    MIGRATION_ID_MAP_ID VARCHAR(36) NOT NULL,
    MIGRATION_BATCH_ID VARCHAR(64) NOT NULL,
    SOURCE_ENTITY VARCHAR(100) NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    TARGET_ID VARCHAR(255) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_MIGRATION_ID_MAP PRIMARY KEY (MIGRATION_ID_MAP_ID),
    CONSTRAINT FK_MIGRATION_ID_MAP_BATCH FOREIGN KEY (MIGRATION_BATCH_ID) REFERENCES EFNS_DEV.RAW.MIGRATION_BATCH (MIGRATION_BATCH_ID),
    CONSTRAINT UQ_MIGRATION_SOURCE_ID UNIQUE (MIGRATION_BATCH_ID, SOURCE_ENTITY, SOURCE_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.MIGRATION_ERROR (
    MIGRATION_ERROR_ID VARCHAR(36) NOT NULL,
    MIGRATION_BATCH_ID VARCHAR(64) NOT NULL,
    SOURCE_FILENAME VARCHAR(500) NOT NULL,
    SOURCE_ENTITY VARCHAR(100) NOT NULL,
    SOURCE_ROW_NUMBER NUMBER(18,0) NOT NULL,
    FIELD_NAME VARCHAR(255),
    ERROR_CATEGORY VARCHAR(100) DEFAULT 'VALIDATION',
    ERROR_MESSAGE VARCHAR(2000) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_MIGRATION_ERROR PRIMARY KEY (MIGRATION_ERROR_ID),
    CONSTRAINT FK_MIGRATION_ERROR_BATCH FOREIGN KEY (MIGRATION_BATCH_ID) REFERENCES EFNS_DEV.RAW.MIGRATION_BATCH (MIGRATION_BATCH_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.MIGRATION_RECONCILIATION (
    MIGRATION_RECONCILIATION_ID VARCHAR(36) NOT NULL,
    MIGRATION_BATCH_ID VARCHAR(64) NOT NULL,
    SOURCE_ENTITY VARCHAR(100) NOT NULL,
    SOURCE_ROWS NUMBER(18,0) NOT NULL,
    READY_ROWS NUMBER(18,0) NOT NULL,
    REJECTED_ROWS NUMBER(18,0) NOT NULL,
    INSERTED_ROWS NUMBER(18,0) NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_MIGRATION_RECONCILIATION PRIMARY KEY (MIGRATION_RECONCILIATION_ID),
    CONSTRAINT FK_MIGRATION_RECONCILIATION_BATCH FOREIGN KEY (MIGRATION_BATCH_ID) REFERENCES EFNS_DEV.RAW.MIGRATION_BATCH (MIGRATION_BATCH_ID),
    CONSTRAINT UQ_MIGRATION_RECONCILIATION UNIQUE (MIGRATION_BATCH_ID, SOURCE_ENTITY)
);

-- Full source rows, including SCRIBE_ID and unmapped Dataverse fields, remain
-- in MIGRATION_RAW_ROW.RAW_DATA. SOURCE_ID stores the mapped Dataverse key.

-- ============================================================
-- 4. Additive upgrades for an existing EFNS_DEV schema
-- ============================================================

ALTER TABLE IF EXISTS EFNS_DEV.CORE.FARM_LOCATION ADD COLUMN IF NOT EXISTS FAX VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FARM_LOCATION ADD COLUMN IF NOT EXISTS EIMS_LOCATION_ID VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY ADD COLUMN IF NOT EXISTS FARM_LOCATION_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY ADD COLUMN IF NOT EXISTS HOUSING_SYSTEM VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY ADD COLUMN IF NOT EXISTS RENOVATION_DATE DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY ADD COLUMN IF NOT EXISTS FACILITY_QUOTA NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY ADD COLUMN IF NOT EXISTS MANURE_DISPOSAL VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY ADD COLUMN IF NOT EXISTS COMMENTS VARCHAR(4000);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS EIMS_FACILITY_DETAIL_ID VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS BIRD_COLOUR VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS BIRDS_HOUSED NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS CAGE_BRAND VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS DATE_INSTALLED DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS HEIGHT NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS HIGHEST_BIRDS_PER_CAGE NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS LENGTH NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS NUMBER_OF_CAGES NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS SQUARE_INCHES NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS WIDTH NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.SALMONELLA_TEST ADD COLUMN IF NOT EXISTS TEST_TYPE VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE ADD COLUMN IF NOT EXISTS TEST_AREA VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE ADD COLUMN IF NOT EXISTS SEROTYPE VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE ADD COLUMN IF NOT EXISTS PHAGE VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE ADD COLUMN IF NOT EXISTS STATUS VARCHAR(100);

-- Defensive writer-contract upgrades for operational tables that can predate
-- EIMS v3. Existing columns are left unchanged.
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS FLOCK_NUMBER VARCHAR(64);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS ACCOUNT_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS FACILITY_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS FACILITY_DETAIL_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS QUOTA_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS FLOCK_QUOTA_TYPE VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS STATUS VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS CREATE_DELIVERY_TRANSACTION BOOLEAN;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS PERMIT_NUMBER VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS PERMIT_DATE DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS HATCH_DATE DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS DATE_ORDERED DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS BIRD_COUNT NUMBER(12,0);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS EGG_COLOUR VARCHAR(50);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS BIRD_STRAIN VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS PLACEMENT_DATE DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS EST_DISPOSAL DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS DISPOSAL_DATE DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS BIRDS_DISPOSED NUMBER(12,0);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS BREEDER VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS HATCHERY VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS PULLET_GROWER VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS DISPOSAL_PLANT VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS DISPOSAL_METHOD VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK ADD COLUMN IF NOT EXISTS COMMENTS VARCHAR(2000);

ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK_TRANSACTION ADD COLUMN IF NOT EXISTS FLOCK_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK_TRANSACTION ADD COLUMN IF NOT EXISTS TRANSACTION_TYPE VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK_TRANSACTION ADD COLUMN IF NOT EXISTS QUANTITY NUMBER(12,2);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK_TRANSACTION ADD COLUMN IF NOT EXISTS TRANSACTION_DATE DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FLOCK_TRANSACTION ADD COLUMN IF NOT EXISTS NOTES VARCHAR(2000);

ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_REGISTRATION ADD COLUMN IF NOT EXISTS REGISTRATION_NUMBER VARCHAR(64);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_REGISTRATION ADD COLUMN IF NOT EXISTS ACCOUNT_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_REGISTRATION ADD COLUMN IF NOT EXISTS QUOTA_NAME VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_REGISTRATION ADD COLUMN IF NOT EXISTS QUOTA_TYPE VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_REGISTRATION ADD COLUMN IF NOT EXISTS STATUS VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_REGISTRATION ADD COLUMN IF NOT EXISTS EFFECTIVE_DATE DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_REGISTRATION ADD COLUMN IF NOT EXISTS END_DATE DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_REGISTRATION ADD COLUMN IF NOT EXISTS COMMENTS VARCHAR(2000);

ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION ADD COLUMN IF NOT EXISTS TRANSACTION_TYPE VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION ADD COLUMN IF NOT EXISTS QUOTA_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION ADD COLUMN IF NOT EXISTS EFFECTIVE_DATE DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION ADD COLUMN IF NOT EXISTS END_DATE DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION ADD COLUMN IF NOT EXISTS QUOTA_COUNT NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION ADD COLUMN IF NOT EXISTS OWNER_ACCOUNT_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION ADD COLUMN IF NOT EXISTS RELATED_ACCOUNT_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION ADD COLUMN IF NOT EXISTS RELATED_QUOTA_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION ADD COLUMN IF NOT EXISTS RELATED_TRANSACTION_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION ADD COLUMN IF NOT EXISTS PRICE NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION ADD COLUMN IF NOT EXISTS QUOTA_LEASE_TYPE VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.QUOTA_TRANSACTION ADD COLUMN IF NOT EXISTS COMMENTS VARCHAR(2000);

ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS PRODUCER_ACCOUNT_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS GRADER_ACCOUNT_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS FACILITY_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS FLOCK_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS GRADER_NAME VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS PRODUCER_NUMBER VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS GRADER_NUMBER VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS BARN_IDENTITY VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS SOURCE_WEEK_CODE VARCHAR(20);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS REPORTING_YEAR NUMBER(4,0);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS REPORTING_WEEK NUMBER(2,0);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS MARKETING_TYPE VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS HOUSING_SYSTEM VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS EGG_TYPE VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS EGG_COLOUR VARCHAR(50);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS FLOCK_AGE NUMBER(10,0);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS NET_WEIGHT NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS NET_BOXES NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS NET_PER_BOX NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS JUMBO NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS EXTRA_LARGE NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS LARGE NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS MEDIUM NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS SMALL NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS PEEWEE NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS GRADE_B NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS GRADE_C NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS CRACKS NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS NEST_RUN NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS NEST_RUN_25_PLUS NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS NEST_RUN_24_PLUS NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS NEST_RUN_23_PLUS NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS NEST_RUN_22_PLUS NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS NEST_RUN_21_PLUS NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS NEST_RUN_20_PLUS NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS NEST_RUN_19_PLUS NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS NEST_RUN_18_PLUS NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS NEST_RUN_17_PLUS NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS OTHER_LEVIABLE NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS OTHER_NON_LEVIABLE NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS FARM_GATE_SALES NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS ON_FARM_CONSUMPTION NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS SUBTOTAL NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS REJECTS NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS LEAKERS NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS TOTAL NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS TOTAL_RECEIVED NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS REJECTED NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS LOSS NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS LEGACY_REJECT_LOSS_TOTAL NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS TOTAL_ACCEPTED NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS SOURCE_TYPE VARCHAR(50);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS MATCH_STATUS VARCHAR(50);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS SOURCE_ROW_NUMBER NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS MATCH_CONFIRMED_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.PRODUCTION_RECORD ADD COLUMN IF NOT EXISTS MATCH_CONFIRMED_BY VARCHAR(255);

-- Defensive upgrades for every column written by the migration repository.
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_BATCH ADD COLUMN IF NOT EXISTS MIGRATION_BATCH_ID VARCHAR(64);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_BATCH ADD COLUMN IF NOT EXISTS PACKAGE_HASH VARCHAR(64);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_BATCH ADD COLUMN IF NOT EXISTS SCHEMA_VERSION VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_BATCH ADD COLUMN IF NOT EXISTS STATUS VARCHAR(30);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_BATCH ADD COLUMN IF NOT EXISTS SOURCE_FILE_COUNT NUMBER(10,0);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_BATCH ADD COLUMN IF NOT EXISTS SOURCE_ROW_COUNT NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_BATCH ADD COLUMN IF NOT EXISTS READY_ROW_COUNT NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_BATCH ADD COLUMN IF NOT EXISTS REJECTED_ROW_COUNT NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_BATCH ADD COLUMN IF NOT EXISTS CREATED_BY VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_BATCH ADD COLUMN IF NOT EXISTS COMMITTED_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_BATCH ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_BATCH ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_FILE ADD COLUMN IF NOT EXISTS MIGRATION_FILE_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_FILE ADD COLUMN IF NOT EXISTS MIGRATION_BATCH_ID VARCHAR(64);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_FILE ADD COLUMN IF NOT EXISTS SOURCE_FILENAME VARCHAR(500);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_FILE ADD COLUMN IF NOT EXISTS SOURCE_ENTITY VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_FILE ADD COLUMN IF NOT EXISTS FILE_HASH VARCHAR(64);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_FILE ADD COLUMN IF NOT EXISTS FILE_SIZE_BYTES NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_FILE ADD COLUMN IF NOT EXISTS SOURCE_ROW_COUNT NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_FILE ADD COLUMN IF NOT EXISTS STAGE_PATH VARCHAR(1000);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_FILE ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS MIGRATION_RAW_ROW_ID VARCHAR(64);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS MIGRATION_BATCH_ID VARCHAR(64);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS SOURCE_FILENAME VARCHAR(500);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS SOURCE_ENTITY VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS SOURCE_ROW_NUMBER NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS SOURCE_ID VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS TARGET_ID VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS RAW_DATA VARIANT;
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS NORMALIZED_DATA VARIANT;
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS VALIDATION_STATUS VARCHAR(30);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS MATCH_STATUS VARCHAR(30);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS VALIDATION_MESSAGES VARIANT;
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ID_MAP ADD COLUMN IF NOT EXISTS MIGRATION_ID_MAP_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ID_MAP ADD COLUMN IF NOT EXISTS MIGRATION_BATCH_ID VARCHAR(64);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ID_MAP ADD COLUMN IF NOT EXISTS SOURCE_ENTITY VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ID_MAP ADD COLUMN IF NOT EXISTS SOURCE_ID VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ID_MAP ADD COLUMN IF NOT EXISTS TARGET_ID VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ID_MAP ADD COLUMN IF NOT EXISTS STATUS VARCHAR(30);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ID_MAP ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ID_MAP ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ERROR ADD COLUMN IF NOT EXISTS MIGRATION_ERROR_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ERROR ADD COLUMN IF NOT EXISTS MIGRATION_BATCH_ID VARCHAR(64);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ERROR ADD COLUMN IF NOT EXISTS SOURCE_FILENAME VARCHAR(500);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ERROR ADD COLUMN IF NOT EXISTS SOURCE_ENTITY VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ERROR ADD COLUMN IF NOT EXISTS SOURCE_ROW_NUMBER NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ERROR ADD COLUMN IF NOT EXISTS FIELD_NAME VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ERROR ADD COLUMN IF NOT EXISTS ERROR_MESSAGE VARCHAR(2000);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ERROR ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RECONCILIATION ADD COLUMN IF NOT EXISTS MIGRATION_RECONCILIATION_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RECONCILIATION ADD COLUMN IF NOT EXISTS MIGRATION_BATCH_ID VARCHAR(64);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RECONCILIATION ADD COLUMN IF NOT EXISTS SOURCE_ENTITY VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RECONCILIATION ADD COLUMN IF NOT EXISTS SOURCE_ROWS NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RECONCILIATION ADD COLUMN IF NOT EXISTS READY_ROWS NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RECONCILIATION ADD COLUMN IF NOT EXISTS REJECTED_ROWS NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RECONCILIATION ADD COLUMN IF NOT EXISTS INSERTED_ROWS NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RECONCILIATION ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_RECONCILIATION ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP_NTZ;

-- Snowflake does not allow DEFAULT together with ADD COLUMN IF NOT EXISTS.
-- A newly created table receives the default above; an upgraded table receives
-- the nullable category column and migration writers may set it explicitly.
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ERROR ADD COLUMN IF NOT EXISTS ERROR_CATEGORY VARCHAR(100);

-- Relax only constraints known to reject valid historical v3 values.
EXECUTE IMMEDIATE $$
BEGIN
    IF (EXISTS (SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'FLOCK'
                 AND COLUMN_NAME = 'FACILITY_ID' AND IS_NULLABLE = 'NO')) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.FLOCK ALTER COLUMN FACILITY_ID DROP NOT NULL';
    END IF;
    IF (EXISTS (SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'QUOTA_TRANSACTION'
                 AND COLUMN_NAME = 'RELATED_ACCOUNT_ID' AND IS_NULLABLE = 'NO')) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.QUOTA_TRANSACTION ALTER COLUMN RELATED_ACCOUNT_ID DROP NOT NULL';
    END IF;
    IF (EXISTS (SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'SALMONELLA_TEST'
                 AND COLUMN_NAME = 'NUMBER_OF_SAMPLES' AND IS_NULLABLE = 'NO')) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.SALMONELLA_TEST ALTER COLUMN NUMBER_OF_SAMPLES DROP NOT NULL';
    END IF;
    IF (EXISTS (SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'SALMONELLA_TEST'
                 AND COLUMN_NAME = 'TEST_RESULT' AND IS_NULLABLE = 'NO')) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.SALMONELLA_TEST ALTER COLUMN TEST_RESULT DROP NOT NULL';
    END IF;
    IF (EXISTS (SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'QUOTA_TRANSACTION'
                 AND CONSTRAINT_NAME = 'CK_QUOTA_TRANSACTION_COUNT')) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.QUOTA_TRANSACTION DROP CONSTRAINT CK_QUOTA_TRANSACTION_COUNT';
    END IF;
    IF (EXISTS (SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'SALMONELLA_TEST'
                 AND CONSTRAINT_NAME = 'CK_SALMONELLA_SAMPLE_COUNT')) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.SALMONELLA_TEST DROP CONSTRAINT CK_SALMONELLA_SAMPLE_COUNT';
    END IF;
    IF (EXISTS (
        SELECT 1
        FROM EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
        JOIN EFNS_DEV.INFORMATION_SCHEMA.CHECK_CONSTRAINTS CC
          ON CC.CONSTRAINT_SCHEMA = TC.CONSTRAINT_SCHEMA
         AND CC.CONSTRAINT_NAME = TC.CONSTRAINT_NAME
        WHERE TC.TABLE_SCHEMA = 'CORE' AND TC.TABLE_NAME = 'FLOCK_TRANSACTION'
          AND TC.CONSTRAINT_NAME = 'CK_FLOCK_TRANSACTION_QUANTITY'
          AND REPLACE(UPPER(CC.CHECK_CLAUSE), ' ', '') NOT LIKE '%QUANTITY>=0%'
    )) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.FLOCK_TRANSACTION DROP CONSTRAINT CK_FLOCK_TRANSACTION_QUANTITY';
    END IF;
    IF (NOT EXISTS (SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS
                   WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'FLOCK_TRANSACTION'
                     AND CONSTRAINT_NAME = 'CK_FLOCK_TRANSACTION_QUANTITY')) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.FLOCK_TRANSACTION ADD CONSTRAINT CK_FLOCK_TRANSACTION_QUANTITY CHECK (QUANTITY >= 0)';
    END IF;
END;
$$;

-- Add v3 relationships when upgrading tables that already existed.
EXECUTE IMMEDIATE $$
BEGIN
    IF (NOT EXISTS (SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS
                   WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'FACILITY'
                     AND CONSTRAINT_NAME = 'FK_FACILITY_FARM_LOCATION')) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.FACILITY ADD CONSTRAINT FK_FACILITY_FARM_LOCATION FOREIGN KEY (FARM_LOCATION_ID) REFERENCES EFNS_DEV.CORE.FARM_LOCATION (FARM_LOCATION_ID)';
    END IF;
    IF (NOT EXISTS (SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS
                   WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'QUOTA_TRANSACTION'
                     AND CONSTRAINT_NAME = 'FK_QUOTA_TRANSACTION_RELATED_QUOTA')) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.QUOTA_TRANSACTION ADD CONSTRAINT FK_QUOTA_TRANSACTION_RELATED_QUOTA FOREIGN KEY (RELATED_QUOTA_ID) REFERENCES EFNS_DEV.CORE.QUOTA_REGISTRATION (QUOTA_ID)';
    END IF;
    IF (NOT EXISTS (SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS
                   WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'QUOTA_TRANSACTION'
                     AND CONSTRAINT_NAME = 'FK_QUOTA_TRANSACTION_RELATED_TRANSACTION')) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.QUOTA_TRANSACTION ADD CONSTRAINT FK_QUOTA_TRANSACTION_RELATED_TRANSACTION FOREIGN KEY (RELATED_TRANSACTION_ID) REFERENCES EFNS_DEV.CORE.QUOTA_TRANSACTION (QUOTA_TRANSACTION_ID)';
    END IF;
    IF (NOT EXISTS (SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS
                   WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'PRODUCTION_RECORD'
                     AND CONSTRAINT_NAME = 'FK_PRODUCTION_GRADER_ACCOUNT')) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.PRODUCTION_RECORD ADD CONSTRAINT FK_PRODUCTION_GRADER_ACCOUNT FOREIGN KEY (GRADER_ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID)';
    END IF;
END;
$$;

-- Exact application grants for the v3 additions.
GRANT READ, WRITE ON STAGE EFNS_DEV.RAW.EIMS_MIGRATION_FILES TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE EFNS_DEV.CORE.CONTACT TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE EFNS_DEV.CORE.QUOTA_ALLOCATION TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE ON TABLE EFNS_DEV.CORE.DIM_EFC_DATE TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE ON TABLE EFNS_DEV.RAW.MIGRATION_BATCH TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT ON TABLE EFNS_DEV.RAW.MIGRATION_FILE TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT ON TABLE EFNS_DEV.RAW.MIGRATION_RAW_ROW TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE ON TABLE EFNS_DEV.RAW.MIGRATION_ID_MAP TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT ON TABLE EFNS_DEV.RAW.MIGRATION_ERROR TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE ON TABLE EFNS_DEV.RAW.MIGRATION_RECONCILIATION TO ROLE EFNS_DEV_APP_OWNER;

-- ============================================================
-- 5. Verification: metadata and counts only, no PII
-- ============================================================

SELECT
    CURRENT_ROLE() AS CURRENT_ROLE,
    CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE,
    CURRENT_DATABASE() AS CURRENT_DATABASE,
    CURRENT_SCHEMA() AS CURRENT_SCHEMA;

WITH EXPECTED(TABLE_SCHEMA, TABLE_NAME) AS (
    SELECT * FROM VALUES
      ('CORE','ACCOUNT'), ('CORE','CONTACT'), ('CORE','FARM_LOCATION'), ('CORE','FACILITY'),
      ('CORE','FACILITY_DETAIL'), ('CORE','QUOTA_REGISTRATION'), ('CORE','FLOCK'),
      ('CORE','FLOCK_TRANSACTION'), ('CORE','QUOTA_TRANSACTION'), ('CORE','SALMONELLA_TEST'),
      ('CORE','SALMONELLA_TEST_SAMPLE'), ('CORE','PRODUCTION_RECORD'),
      ('CORE','QUOTA_ALLOCATION'), ('CORE','DIM_EFC_DATE'),
      ('RAW','MIGRATION_BATCH'), ('RAW','MIGRATION_FILE'), ('RAW','MIGRATION_RAW_ROW'),
      ('RAW','MIGRATION_ID_MAP'), ('RAW','MIGRATION_ERROR'), ('RAW','MIGRATION_RECONCILIATION')
)
SELECT E.TABLE_SCHEMA, E.TABLE_NAME,
       IFF(T.TABLE_NAME IS NULL, 'MISSING', 'PRESENT') AS DEPLOYMENT_STATUS
FROM EXPECTED E
LEFT JOIN EFNS_DEV.INFORMATION_SCHEMA.TABLES T
  ON T.TABLE_SCHEMA = E.TABLE_SCHEMA AND T.TABLE_NAME = E.TABLE_NAME
ORDER BY E.TABLE_SCHEMA, E.TABLE_NAME;

WITH REQUIRED(TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME) AS (
    SELECT * FROM VALUES
      ('CORE','CONTACT','CONTACT_ID'), ('CORE','CONTACT','ACCOUNT_ID'),
      ('CORE','QUOTA_ALLOCATION','QUOTA_ALLOCATION_ID'),
      ('CORE','DIM_EFC_DATE','DAY'), ('CORE','DIM_EFC_DATE','ELEMENT_CODES'),
      ('CORE','FACILITY','FARM_LOCATION_ID'), ('CORE','FLOCK','FACILITY_ID'),
      ('CORE','QUOTA_TRANSACTION','RELATED_ACCOUNT_ID'),
      ('CORE','SALMONELLA_TEST','TEST_TYPE'), ('CORE','SALMONELLA_TEST_SAMPLE','TEST_AREA'),
      ('CORE','PRODUCTION_RECORD','PRODUCTION_ID'), ('CORE','PRODUCTION_RECORD','GRADER_ACCOUNT_ID'),
      ('RAW','MIGRATION_BATCH','STATUS'), ('RAW','MIGRATION_BATCH','READY_ROW_COUNT'),
      ('RAW','MIGRATION_FILE','SOURCE_FILENAME'), ('RAW','MIGRATION_FILE','SOURCE_ROW_COUNT'),
      ('RAW','MIGRATION_RAW_ROW','SOURCE_ROW_NUMBER'), ('RAW','MIGRATION_RAW_ROW','SOURCE_ID'),
      ('RAW','MIGRATION_RAW_ROW','RAW_DATA'), ('RAW','MIGRATION_RAW_ROW','VALIDATION_STATUS'),
      ('RAW','MIGRATION_ERROR','ERROR_CATEGORY'), ('RAW','MIGRATION_ERROR','ERROR_MESSAGE'),
      ('RAW','MIGRATION_RECONCILIATION','INSERTED_ROWS')
)
SELECT R.TABLE_SCHEMA, R.TABLE_NAME, R.COLUMN_NAME,
       IFF(C.COLUMN_NAME IS NULL, 'MISSING', 'PRESENT') AS DEPLOYMENT_STATUS
FROM REQUIRED R
LEFT JOIN EFNS_DEV.INFORMATION_SCHEMA.COLUMNS C
  ON C.TABLE_SCHEMA = R.TABLE_SCHEMA
 AND C.TABLE_NAME = R.TABLE_NAME
 AND C.COLUMN_NAME = R.COLUMN_NAME
ORDER BY R.TABLE_SCHEMA, R.TABLE_NAME, R.COLUMN_NAME;

WITH REQUIRED(CONSTRAINT_SCHEMA, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE) AS (
    SELECT * FROM VALUES
      ('CORE','CONTACT','PK_CONTACT','PRIMARY KEY'),
      ('CORE','CONTACT','FK_CONTACT_ACCOUNT','FOREIGN KEY'),
      ('CORE','FACILITY','FK_FACILITY_FARM_LOCATION','FOREIGN KEY'),
      ('CORE','QUOTA_TRANSACTION','FK_QUOTA_TRANSACTION_RELATED_QUOTA','FOREIGN KEY'),
      ('CORE','QUOTA_TRANSACTION','FK_QUOTA_TRANSACTION_RELATED_TRANSACTION','FOREIGN KEY'),
      ('CORE','PRODUCTION_RECORD','FK_PRODUCTION_GRADER_ACCOUNT','FOREIGN KEY'),
      ('CORE','QUOTA_ALLOCATION','PK_QUOTA_ALLOCATION','PRIMARY KEY'),
      ('CORE','DIM_EFC_DATE','PK_DIM_EFC_DATE','PRIMARY KEY'),
      ('RAW','MIGRATION_ERROR','FK_MIGRATION_ERROR_BATCH','FOREIGN KEY'),
      ('RAW','MIGRATION_RECONCILIATION','FK_MIGRATION_RECONCILIATION_BATCH','FOREIGN KEY')
)
SELECT R.CONSTRAINT_SCHEMA AS TABLE_SCHEMA, R.TABLE_NAME, R.CONSTRAINT_NAME, R.CONSTRAINT_TYPE,
       IFF(C.CONSTRAINT_NAME IS NULL, 'MISSING', 'PRESENT') AS DEPLOYMENT_STATUS
FROM REQUIRED R
LEFT JOIN EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS C
  ON C.CONSTRAINT_SCHEMA = R.CONSTRAINT_SCHEMA
 AND C.TABLE_NAME = R.TABLE_NAME
 AND C.CONSTRAINT_NAME = R.CONSTRAINT_NAME
 AND C.CONSTRAINT_TYPE = R.CONSTRAINT_TYPE
ORDER BY R.CONSTRAINT_SCHEMA, R.TABLE_NAME, R.CONSTRAINT_NAME;

SELECT
    TC.CONSTRAINT_SCHEMA AS TABLE_SCHEMA,
    TC.TABLE_NAME,
    TC.CONSTRAINT_NAME,
    TC.CONSTRAINT_TYPE,
    KCU.COLUMN_NAME,
    KCU.ORDINAL_POSITION
FROM EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
LEFT JOIN EFNS_DEV.INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU
  ON KCU.CONSTRAINT_SCHEMA = TC.CONSTRAINT_SCHEMA
 AND KCU.CONSTRAINT_NAME = TC.CONSTRAINT_NAME
 AND KCU.TABLE_NAME = TC.TABLE_NAME
WHERE TC.TABLE_SCHEMA IN ('CORE', 'RAW')
  AND TC.TABLE_NAME IN (
      'ACCOUNT', 'CONTACT', 'FARM_LOCATION', 'FACILITY', 'FACILITY_DETAIL',
      'QUOTA_REGISTRATION', 'FLOCK', 'FLOCK_TRANSACTION', 'QUOTA_TRANSACTION',
      'SALMONELLA_TEST', 'SALMONELLA_TEST_SAMPLE', 'PRODUCTION_RECORD',
      'QUOTA_ALLOCATION', 'DIM_EFC_DATE', 'MIGRATION_BATCH', 'MIGRATION_FILE',
      'MIGRATION_RAW_ROW', 'MIGRATION_ID_MAP', 'MIGRATION_ERROR',
      'MIGRATION_RECONCILIATION'
  )
ORDER BY TC.CONSTRAINT_SCHEMA, TC.TABLE_NAME, TC.CONSTRAINT_TYPE,
         TC.CONSTRAINT_NAME, KCU.ORDINAL_POSITION;

SELECT 'CORE.ACCOUNT' AS OBJECT_NAME, COUNT(*) AS RECORD_COUNT FROM EFNS_DEV.CORE.ACCOUNT
UNION ALL SELECT 'CORE.CONTACT', COUNT(*) FROM EFNS_DEV.CORE.CONTACT
UNION ALL SELECT 'CORE.FARM_LOCATION', COUNT(*) FROM EFNS_DEV.CORE.FARM_LOCATION
UNION ALL SELECT 'CORE.FACILITY', COUNT(*) FROM EFNS_DEV.CORE.FACILITY
UNION ALL SELECT 'CORE.FACILITY_DETAIL', COUNT(*) FROM EFNS_DEV.CORE.FACILITY_DETAIL
UNION ALL SELECT 'CORE.QUOTA_REGISTRATION', COUNT(*) FROM EFNS_DEV.CORE.QUOTA_REGISTRATION
UNION ALL SELECT 'CORE.FLOCK', COUNT(*) FROM EFNS_DEV.CORE.FLOCK
UNION ALL SELECT 'CORE.FLOCK_TRANSACTION', COUNT(*) FROM EFNS_DEV.CORE.FLOCK_TRANSACTION
UNION ALL SELECT 'CORE.QUOTA_TRANSACTION', COUNT(*) FROM EFNS_DEV.CORE.QUOTA_TRANSACTION
UNION ALL SELECT 'CORE.SALMONELLA_TEST', COUNT(*) FROM EFNS_DEV.CORE.SALMONELLA_TEST
UNION ALL SELECT 'CORE.SALMONELLA_TEST_SAMPLE', COUNT(*) FROM EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE
UNION ALL SELECT 'CORE.PRODUCTION_RECORD', COUNT(*) FROM EFNS_DEV.CORE.PRODUCTION_RECORD
UNION ALL SELECT 'CORE.QUOTA_ALLOCATION', COUNT(*) FROM EFNS_DEV.CORE.QUOTA_ALLOCATION
UNION ALL SELECT 'CORE.DIM_EFC_DATE', COUNT(*) FROM EFNS_DEV.CORE.DIM_EFC_DATE
UNION ALL SELECT 'RAW.MIGRATION_BATCH', COUNT(*) FROM EFNS_DEV.RAW.MIGRATION_BATCH
UNION ALL SELECT 'RAW.MIGRATION_FILE', COUNT(*) FROM EFNS_DEV.RAW.MIGRATION_FILE
UNION ALL SELECT 'RAW.MIGRATION_RAW_ROW', COUNT(*) FROM EFNS_DEV.RAW.MIGRATION_RAW_ROW
UNION ALL SELECT 'RAW.MIGRATION_ERROR', COUNT(*) FROM EFNS_DEV.RAW.MIGRATION_ERROR
UNION ALL SELECT 'RAW.MIGRATION_RECONCILIATION', COUNT(*) FROM EFNS_DEV.RAW.MIGRATION_RECONCILIATION
ORDER BY OBJECT_NAME;

SELECT 'ORPHAN_MIGRATION_FILE' AS CHECK_NAME, COUNT(*) AS ISSUE_COUNT
FROM EFNS_DEV.RAW.MIGRATION_FILE F
LEFT JOIN EFNS_DEV.RAW.MIGRATION_BATCH B ON B.MIGRATION_BATCH_ID = F.MIGRATION_BATCH_ID
WHERE B.MIGRATION_BATCH_ID IS NULL
UNION ALL
SELECT 'ORPHAN_MIGRATION_RAW_ROW', COUNT(*)
FROM EFNS_DEV.RAW.MIGRATION_RAW_ROW R
LEFT JOIN EFNS_DEV.RAW.MIGRATION_BATCH B ON B.MIGRATION_BATCH_ID = R.MIGRATION_BATCH_ID
WHERE B.MIGRATION_BATCH_ID IS NULL
UNION ALL
SELECT 'ORPHAN_MIGRATION_ERROR', COUNT(*)
FROM EFNS_DEV.RAW.MIGRATION_ERROR E
LEFT JOIN EFNS_DEV.RAW.MIGRATION_BATCH B ON B.MIGRATION_BATCH_ID = E.MIGRATION_BATCH_ID
WHERE B.MIGRATION_BATCH_ID IS NULL
UNION ALL
SELECT 'ORPHAN_MIGRATION_RECONCILIATION', COUNT(*)
FROM EFNS_DEV.RAW.MIGRATION_RECONCILIATION R
LEFT JOIN EFNS_DEV.RAW.MIGRATION_BATCH B ON B.MIGRATION_BATCH_ID = R.MIGRATION_BATCH_ID
WHERE B.MIGRATION_BATCH_ID IS NULL
ORDER BY CHECK_NAME;

SELECT TABLE_NAME, COLUMN_NAME, IS_NULLABLE
FROM EFNS_DEV.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE'
  AND (
      (TABLE_NAME = 'FLOCK' AND COLUMN_NAME = 'FACILITY_ID') OR
      (TABLE_NAME = 'QUOTA_TRANSACTION' AND COLUMN_NAME = 'RELATED_ACCOUNT_ID') OR
      (TABLE_NAME = 'SALMONELLA_TEST' AND COLUMN_NAME IN ('NUMBER_OF_SAMPLES', 'TEST_RESULT'))
  )
ORDER BY TABLE_NAME, COLUMN_NAME;

SELECT
    COUNT_IF(CONSTRAINT_NAME = 'CK_QUOTA_TRANSACTION_COUNT') AS DISALLOWED_QUOTA_COUNT_CHECKS,
    COUNT_IF(CONSTRAINT_NAME = 'CK_SALMONELLA_SAMPLE_COUNT') AS DISALLOWED_SALMONELLA_COUNT_CHECKS
FROM EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = 'CORE';

SELECT COUNT(*) - COUNT(DISTINCT DAY) AS DUPLICATE_EFC_DAY_COUNT
FROM EFNS_DEV.CORE.DIM_EFC_DATE;

WITH EXPECTED_OBJECTS(TABLE_SCHEMA, TABLE_NAME) AS (
    SELECT * FROM VALUES
      ('CORE','ACCOUNT'), ('CORE','CONTACT'), ('CORE','FARM_LOCATION'), ('CORE','FACILITY'),
      ('CORE','FACILITY_DETAIL'), ('CORE','QUOTA_REGISTRATION'), ('CORE','FLOCK'),
      ('CORE','FLOCK_TRANSACTION'), ('CORE','QUOTA_TRANSACTION'), ('CORE','SALMONELLA_TEST'),
      ('CORE','SALMONELLA_TEST_SAMPLE'), ('CORE','PRODUCTION_RECORD'),
      ('CORE','QUOTA_ALLOCATION'), ('CORE','DIM_EFC_DATE'),
      ('RAW','IMPORT_BATCH'), ('RAW','MIGRATION_BATCH'), ('RAW','MIGRATION_FILE'),
      ('RAW','MIGRATION_RAW_ROW'), ('RAW','MIGRATION_ID_MAP'), ('RAW','MIGRATION_ERROR'),
      ('RAW','MIGRATION_RECONCILIATION')
),
EXPECTED_COLUMN_LIST(TABLE_SCHEMA, TABLE_NAME, COLUMN_LIST) AS (
    SELECT * FROM VALUES
      ('CORE','ACCOUNT','ACCOUNT_ID,REGISTRATION_NUMBER,ORGANIZATION_NAME,ADDRESS_LINE1,ADDRESS_LINE2,ADDRESS_LINE3,CITY,PROVINCE,POSTAL_CODE,COUNTRY_REGION,LATITUDE,LONGITUDE,CONTACT_NAME,CONTACT_PHONE,CONTACT_EMAIL,FAX,WEBSITE,LICENCE_NUMBER,PARENT_ACCOUNT_ID,GRADING_STATION_ACCOUNT_ID,PULLET_GROWER_ACCOUNT_ID,PROVINCE_OF_REGISTRATION,SPENT_FOWL_PLANS,DEFAULT_ON_REPORTS,NO_SVG,DESCRIPTION,PRODUCER_ROLE,BREEDER_ROLE,HATCHERY_ROLE,PULLET_GROWER_ROLE,GRADER_ROLE,PROCESSOR_BREAKER_ROLE,DISPOSAL_PLANT_ROLE,UNREGULATED_ROLE,PROV_BOARD_EFC_ROLE,GOVERNMENT_ROLE,VENDOR_ROLE,RESEARCH_EXEMPT_ROLE,SHIPPER_ROLE,OTHER_ROLE,STATUS,CREATED_AT,UPDATED_AT'),
      ('CORE','CONTACT','CONTACT_ID,ACCOUNT_ID,FULL_NAME,FIRST_NAME,MIDDLE_NAME,LAST_NAME,JOB_TITLE,EMAIL,PHONE,MOBILE_PHONE,FAX,ADDRESS_LINE1,ADDRESS_LINE2,CITY,PROVINCE,POSTAL_CODE,COUNTRY_REGION,EIMS_CONTACT_NUMBER,LANGUAGE_PREFERENCE,PRIME_CONTACT,STATUS,CREATED_AT,UPDATED_AT'),
      ('CORE','FARM_LOCATION','FARM_LOCATION_ID,ACCOUNT_ID,LOCATION_NAME,ADDRESS_1,ADDRESS_2,CITY,PROVINCE,POSTAL_CODE,PHONE,FAX,EIMS_LOCATION_ID,STATUS,CREATED_AT,UPDATED_AT'),
      ('CORE','FACILITY','FACILITY_ID,ACCOUNT_ID,FARM_LOCATION_ID,FACILITY_NAME,FACILITY_TYPE,HOUSING_SYSTEM,STATUS,ACTIVATION_DATE,CONSTRUCTION_DATE,RENOVATION_DATE,CLOSURE_DATE,DESTRUCTION_DATE,INACTIVE_DATE,FACILITY_QUOTA,MANURE_DISPOSAL,COMMENTS,CREATED_AT,UPDATED_AT'),
      ('CORE','FACILITY_DETAIL','FACILITY_DETAIL_ID,FACILITY_ID,DETAIL_NAME,DETAIL_TYPE,STATUS,COMMENTS,EIMS_FACILITY_DETAIL_ID,BIRD_COLOUR,BIRDS_HOUSED,CAGE_BRAND,DATE_INSTALLED,HEIGHT,HIGHEST_BIRDS_PER_CAGE,LENGTH,NUMBER_OF_CAGES,SQUARE_INCHES,WIDTH,CREATED_AT,UPDATED_AT'),
      ('CORE','QUOTA_REGISTRATION','QUOTA_ID,REGISTRATION_NUMBER,ACCOUNT_ID,QUOTA_NAME,QUOTA_TYPE,STATUS,EFFECTIVE_DATE,END_DATE,COMMENTS,CREATED_AT,UPDATED_AT'),
      ('CORE','FLOCK','FLOCK_ID,FLOCK_NUMBER,ACCOUNT_ID,FACILITY_ID,FACILITY_DETAIL_ID,QUOTA_ID,FLOCK_QUOTA_TYPE,STATUS,CREATE_DELIVERY_TRANSACTION,PERMIT_NUMBER,PERMIT_DATE,HATCH_DATE,DATE_ORDERED,BIRD_COUNT,EGG_COLOUR,BIRD_STRAIN,PLACEMENT_DATE,EST_DISPOSAL,DISPOSAL_DATE,BIRDS_DISPOSED,BREEDER,HATCHERY,PULLET_GROWER,DISPOSAL_PLANT,DISPOSAL_METHOD,COMMENTS,CREATED_AT,UPDATED_AT'),
      ('CORE','FLOCK_TRANSACTION','FLOCK_TRANSACTION_ID,FLOCK_ID,TRANSACTION_TYPE,QUANTITY,TRANSACTION_DATE,NOTES,CREATED_AT,UPDATED_AT'),
      ('CORE','QUOTA_TRANSACTION','QUOTA_TRANSACTION_ID,TRANSACTION_TYPE,QUOTA_ID,EFFECTIVE_DATE,END_DATE,QUOTA_COUNT,OWNER_ACCOUNT_ID,RELATED_ACCOUNT_ID,RELATED_QUOTA_ID,RELATED_TRANSACTION_ID,PRICE,QUOTA_LEASE_TYPE,COMMENTS,CREATED_AT,UPDATED_AT'),
      ('CORE','SALMONELLA_TEST','SALMONELLA_TEST_ID,FLOCK_ID,ACCOUNT_ID,PERMIT_NUMBER,TESTING_DATE,INSPECTOR,NUMBER_OF_SAMPLES,TEST_RESULT,TEST_TYPE,DATE_RESULT_SENT,DATE_RECEIVED,CASE_FILE_NUMBER,INVOICE_NUMBER,INVOICE_DATE,COMMENTS,CREATED_AT,UPDATED_AT'),
      ('CORE','SALMONELLA_TEST_SAMPLE','SALMONELLA_TEST_SAMPLE_ID,SALMONELLA_TEST_ID,SAMPLE_REFERENCE,TEST_AREA,SEROTYPE,PHAGE,STATUS,COMMENTS,CREATED_AT,UPDATED_AT'),
      ('CORE','PRODUCTION_RECORD','PRODUCTION_ID,IMPORT_ID,PRODUCER_ACCOUNT_ID,GRADER_ACCOUNT_ID,FACILITY_ID,FLOCK_ID,GRADER_NAME,PRODUCER_NUMBER,GRADER_NUMBER,BARN_IDENTITY,SOURCE_WEEK_CODE,REPORTING_YEAR,REPORTING_WEEK,MARKETING_TYPE,HOUSING_SYSTEM,EGG_TYPE,EGG_COLOUR,FLOCK_AGE,NET_WEIGHT,NET_BOXES,NET_PER_BOX,JUMBO,EXTRA_LARGE,LARGE,MEDIUM,SMALL,PEEWEE,GRADE_B,GRADE_C,CRACKS,NEST_RUN,NEST_RUN_25_PLUS,NEST_RUN_24_PLUS,NEST_RUN_23_PLUS,NEST_RUN_22_PLUS,NEST_RUN_21_PLUS,NEST_RUN_20_PLUS,NEST_RUN_19_PLUS,NEST_RUN_18_PLUS,NEST_RUN_17_PLUS,OTHER_LEVIABLE,OTHER_NON_LEVIABLE,FARM_GATE_SALES,ON_FARM_CONSUMPTION,SUBTOTAL,REJECTS,LEAKERS,TOTAL,TOTAL_RECEIVED,REJECTED,LOSS,LEGACY_REJECT_LOSS_TOTAL,TOTAL_ACCEPTED,SOURCE_TYPE,MATCH_STATUS,SOURCE_ROW_NUMBER,MATCH_CONFIRMED_AT,MATCH_CONFIRMED_BY,CREATED_AT,UPDATED_AT'),
      ('CORE','QUOTA_ALLOCATION','QUOTA_ALLOCATION_ID,ALLOCATION_COUNT,COMMENTS,EFFECTIVE_DATE,EIMS_ALLOCATION_ID,PROVINCE,QUOTA_TYPE,STATUS,CREATED_AT,UPDATED_AT'),
      ('CORE','DIM_EFC_DATE','DAY,EFC_YEAR,EFC_WEEK_NUMBER,EFC_WEEK,EFC_WEEK_LABEL,EFC_LONG_NAME,EFC_PERIOD,EFC_PERIOD_ALIAS,EFC_QUARTER,ELEMENT_CODE,ELEMENT_CODES,PREVIOUS_QUARTER,PREV_YEAR,PREV_WEEK,PREV_QUARTER,DATE_VALUE,MONTH_NUMBER,MONTH_TEXT,DAYS_IN_MONTH,YEAR_NUMBER,YEAR_MONTH,QUARTER_NUMBER,DAYS_IN_QUARTER,YEAR_QUARTER,DAY_STRING,CREATED_AT,UPDATED_AT'),
      ('RAW','IMPORT_BATCH','IMPORT_ID,FILENAME,SOURCE,FILE_HASH,FILE_SIZE_BYTES,WORKSHEET_NAME,REPORTING_YEAR,REPORTING_WEEK,SOURCE_RECORD_COUNT,ROW_COUNT,ERROR_COUNT,STATUS,NOTES,UPLOAD_TIMESTAMP,CREATED_AT,UPDATED_AT'),
      ('RAW','MIGRATION_BATCH','MIGRATION_BATCH_ID,PACKAGE_HASH,SCHEMA_VERSION,STATUS,SOURCE_FILE_COUNT,SOURCE_ROW_COUNT,READY_ROW_COUNT,REJECTED_ROW_COUNT,CREATED_BY,COMMITTED_AT,CREATED_AT,UPDATED_AT'),
      ('RAW','MIGRATION_FILE','MIGRATION_FILE_ID,MIGRATION_BATCH_ID,SOURCE_FILENAME,SOURCE_ENTITY,FILE_HASH,FILE_SIZE_BYTES,SOURCE_ROW_COUNT,STAGE_PATH,CREATED_AT'),
      ('RAW','MIGRATION_RAW_ROW','MIGRATION_RAW_ROW_ID,MIGRATION_BATCH_ID,SOURCE_FILENAME,SOURCE_ENTITY,SOURCE_ROW_NUMBER,SOURCE_ID,TARGET_ID,RAW_DATA,NORMALIZED_DATA,VALIDATION_STATUS,MATCH_STATUS,VALIDATION_MESSAGES,CREATED_AT,UPDATED_AT'),
      ('RAW','MIGRATION_ID_MAP','MIGRATION_ID_MAP_ID,MIGRATION_BATCH_ID,SOURCE_ENTITY,SOURCE_ID,TARGET_ID,STATUS,CREATED_AT,UPDATED_AT'),
      ('RAW','MIGRATION_ERROR','MIGRATION_ERROR_ID,MIGRATION_BATCH_ID,SOURCE_FILENAME,SOURCE_ENTITY,SOURCE_ROW_NUMBER,FIELD_NAME,ERROR_CATEGORY,ERROR_MESSAGE,CREATED_AT'),
      ('RAW','MIGRATION_RECONCILIATION','MIGRATION_RECONCILIATION_ID,MIGRATION_BATCH_ID,SOURCE_ENTITY,SOURCE_ROWS,READY_ROWS,REJECTED_ROWS,INSERTED_ROWS,CREATED_AT,UPDATED_AT')
),
EXPECTED_COLUMNS AS (
    SELECT L.TABLE_SCHEMA, L.TABLE_NAME, TRIM(S.VALUE::STRING) AS COLUMN_NAME
    FROM EXPECTED_COLUMN_LIST L,
         LATERAL SPLIT_TO_TABLE(L.COLUMN_LIST, ',') S
),
EXPECTED_CONSTRAINTS(CONSTRAINT_SCHEMA, TABLE_NAME, CONSTRAINT_NAME) AS (
    SELECT * FROM VALUES
      ('CORE','ACCOUNT','PK_ACCOUNT'), ('CORE','ACCOUNT','FK_ACCOUNT_PARENT'),
      ('CORE','ACCOUNT','FK_ACCOUNT_GRADING_STATION'), ('CORE','ACCOUNT','FK_ACCOUNT_PULLET_GROWER'),
      ('CORE','CONTACT','PK_CONTACT'), ('CORE','CONTACT','FK_CONTACT_ACCOUNT'),
      ('CORE','FARM_LOCATION','PK_FARM_LOCATION'), ('CORE','FARM_LOCATION','FK_FARM_LOCATION_ACCOUNT'),
      ('CORE','FACILITY','PK_FACILITY'), ('CORE','FACILITY','FK_FACILITY_ACCOUNT'),
      ('CORE','FACILITY','FK_FACILITY_FARM_LOCATION'),
      ('CORE','FACILITY_DETAIL','PK_FACILITY_DETAIL'), ('CORE','FACILITY_DETAIL','FK_FACILITY_DETAIL_FACILITY'),
      ('CORE','QUOTA_REGISTRATION','PK_QUOTA_REGISTRATION'), ('CORE','QUOTA_REGISTRATION','FK_QUOTA_ACCOUNT'),
      ('CORE','FLOCK','PK_FLOCK'), ('CORE','FLOCK','FK_FLOCK_ACCOUNT'),
      ('CORE','FLOCK','FK_FLOCK_FACILITY'), ('CORE','FLOCK','FK_FLOCK_DETAIL'), ('CORE','FLOCK','FK_FLOCK_QUOTA'),
      ('CORE','FLOCK_TRANSACTION','PK_FLOCK_TRANSACTION'), ('CORE','FLOCK_TRANSACTION','FK_FLOCK_TRANSACTION_FLOCK'),
      ('CORE','QUOTA_TRANSACTION','PK_QUOTA_TRANSACTION'), ('CORE','QUOTA_TRANSACTION','FK_QUOTA_TRANSACTION_QUOTA'),
      ('CORE','QUOTA_TRANSACTION','FK_QUOTA_TRANSACTION_OWNER'),
      ('CORE','QUOTA_TRANSACTION','FK_QUOTA_TRANSACTION_RELATED_ACCOUNT'),
      ('CORE','QUOTA_TRANSACTION','FK_QUOTA_TRANSACTION_RELATED_QUOTA'),
      ('CORE','QUOTA_TRANSACTION','FK_QUOTA_TRANSACTION_RELATED_TRANSACTION'),
      ('CORE','SALMONELLA_TEST','PK_SALMONELLA_TEST'), ('CORE','SALMONELLA_TEST','FK_SALMONELLA_TEST_FLOCK'),
      ('CORE','SALMONELLA_TEST','FK_SALMONELLA_TEST_ACCOUNT'),
      ('CORE','SALMONELLA_TEST_SAMPLE','PK_SALMONELLA_TEST_SAMPLE'),
      ('CORE','SALMONELLA_TEST_SAMPLE','FK_SALMONELLA_SAMPLE_TEST'),
      ('CORE','PRODUCTION_RECORD','PK_PRODUCTION_RECORD'), ('CORE','PRODUCTION_RECORD','FK_PRODUCTION_IMPORT'),
      ('CORE','PRODUCTION_RECORD','FK_PRODUCTION_ACCOUNT'), ('CORE','PRODUCTION_RECORD','FK_PRODUCTION_GRADER_ACCOUNT'),
      ('CORE','PRODUCTION_RECORD','FK_PRODUCTION_FACILITY'), ('CORE','PRODUCTION_RECORD','FK_PRODUCTION_FLOCK'),
      ('CORE','QUOTA_ALLOCATION','PK_QUOTA_ALLOCATION'), ('CORE','DIM_EFC_DATE','PK_DIM_EFC_DATE'),
      ('RAW','IMPORT_BATCH','PK_IMPORT_BATCH'), ('RAW','MIGRATION_BATCH','PK_MIGRATION_BATCH'),
      ('RAW','MIGRATION_FILE','PK_MIGRATION_FILE'), ('RAW','MIGRATION_FILE','FK_MIGRATION_FILE_BATCH'),
      ('RAW','MIGRATION_RAW_ROW','PK_MIGRATION_RAW_ROW'), ('RAW','MIGRATION_RAW_ROW','FK_MIGRATION_RAW_ROW_BATCH'),
      ('RAW','MIGRATION_ID_MAP','PK_MIGRATION_ID_MAP'), ('RAW','MIGRATION_ID_MAP','FK_MIGRATION_ID_MAP_BATCH'),
      ('RAW','MIGRATION_ERROR','PK_MIGRATION_ERROR'), ('RAW','MIGRATION_ERROR','FK_MIGRATION_ERROR_BATCH'),
      ('RAW','MIGRATION_RECONCILIATION','PK_MIGRATION_RECONCILIATION'),
      ('RAW','MIGRATION_RECONCILIATION','FK_MIGRATION_RECONCILIATION_BATCH')
),
MISSING AS (
    SELECT
      (SELECT COUNT(*) FROM EXPECTED_OBJECTS E
       LEFT JOIN EFNS_DEV.INFORMATION_SCHEMA.TABLES T
         ON T.TABLE_SCHEMA = E.TABLE_SCHEMA AND T.TABLE_NAME = E.TABLE_NAME
       WHERE T.TABLE_NAME IS NULL) AS MISSING_OBJECTS,
      (SELECT COUNT(*) FROM EXPECTED_COLUMNS E
       LEFT JOIN EFNS_DEV.INFORMATION_SCHEMA.COLUMNS C
         ON C.TABLE_SCHEMA = E.TABLE_SCHEMA AND C.TABLE_NAME = E.TABLE_NAME
        AND C.COLUMN_NAME = E.COLUMN_NAME
       WHERE C.COLUMN_NAME IS NULL) AS MISSING_COLUMNS,
      (SELECT COUNT(*) FROM EXPECTED_CONSTRAINTS E
       LEFT JOIN EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS C
         ON C.CONSTRAINT_SCHEMA = E.CONSTRAINT_SCHEMA AND C.TABLE_NAME = E.TABLE_NAME
        AND C.CONSTRAINT_NAME = E.CONSTRAINT_NAME
       WHERE C.CONSTRAINT_NAME IS NULL) AS MISSING_CONSTRAINTS,
      (SELECT COUNT(*)
       FROM SNOWFLAKE.ACCOUNT_USAGE.ROLES
       WHERE NAME = 'EFNS_DEV_APP_OWNER' AND DELETED_ON IS NULL) AS APP_OWNER_ROLE_COUNT
)
SELECT MISSING_OBJECTS AS MISSING_REQUIRED_OBJECTS,
       MISSING_COLUMNS AS MISSING_REQUIRED_COLUMNS,
       MISSING_CONSTRAINTS AS MISSING_REQUIRED_CONSTRAINTS,
       IFF(APP_OWNER_ROLE_COUNT > 0, 'PRESENT', 'MISSING') AS EFNS_DEV_APP_OWNER_ROLE,
       IFF(MISSING_OBJECTS + MISSING_COLUMNS + MISSING_CONSTRAINTS = 0
           AND APP_OWNER_ROLE_COUNT > 0,
           'READY_FOR_EIMS_V3_VALIDATION', 'NOT_READY') AS FINAL_STATUS
FROM MISSING;

