-- EFNS DEV / PROVISIONAL historical EIMS migration foundation.
-- Reviewed for EFNS_DEV only. This script does not change operational schemas.

-- SYSADMIN owns the database schemas created by sql/01_setup.sql and creates
-- these DEV objects. SECURITYADMIN applies only the exact runtime grants.
USE ROLE SYSADMIN;

CREATE STAGE IF NOT EXISTS EFNS_DEV.RAW.EIMS_MIGRATION_FILES
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Encrypted internal stage for provisional EIMS migration packages';

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.MIGRATION_BATCH (
    MIGRATION_BATCH_ID VARCHAR(64) NOT NULL,
    PACKAGE_HASH VARCHAR(64) NOT NULL,
    SCHEMA_VERSION VARCHAR(100) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    SOURCE_FILE_COUNT NUMBER(10,0) NOT NULL,
    SOURCE_ROW_COUNT NUMBER(18,0) NOT NULL,
    READY_ROW_COUNT NUMBER(18,0) NOT NULL,
    REJECTED_ROW_COUNT NUMBER(18,0) NOT NULL,
    CREATED_BY VARCHAR(255),
    COMMITTED_AT TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_MIGRATION_BATCH PRIMARY KEY (MIGRATION_BATCH_ID),
    CONSTRAINT UQ_MIGRATION_BATCH_HASH UNIQUE (PACKAGE_HASH)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.MIGRATION_FILE (
    MIGRATION_FILE_ID VARCHAR(36) NOT NULL,
    MIGRATION_BATCH_ID VARCHAR(64) NOT NULL,
    SOURCE_FILENAME VARCHAR(500) NOT NULL,
    SOURCE_ENTITY VARCHAR(100) NOT NULL,
    FILE_HASH VARCHAR(64) NOT NULL,
    FILE_SIZE_BYTES NUMBER(18,0),
    SOURCE_ROW_COUNT NUMBER(18,0),
    STAGE_PATH VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_MIGRATION_FILE PRIMARY KEY (MIGRATION_FILE_ID),
    CONSTRAINT FK_MIGRATION_FILE_BATCH FOREIGN KEY (MIGRATION_BATCH_ID)
        REFERENCES EFNS_DEV.RAW.MIGRATION_BATCH (MIGRATION_BATCH_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.MIGRATION_RAW_ROW (
    MIGRATION_RAW_ROW_ID VARCHAR(64) NOT NULL,
    MIGRATION_BATCH_ID VARCHAR(64) NOT NULL,
    SOURCE_FILENAME VARCHAR(500) NOT NULL,
    SOURCE_ENTITY VARCHAR(100) NOT NULL,
    SOURCE_ROW_NUMBER NUMBER(18,0) NOT NULL,
    SOURCE_ID VARCHAR(255),
    TARGET_ID VARCHAR(255),
    RAW_DATA VARIANT NOT NULL,
    NORMALIZED_DATA VARIANT,
    VALIDATION_STATUS VARCHAR(30) NOT NULL,
    MATCH_STATUS VARCHAR(30),
    VALIDATION_MESSAGES VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_MIGRATION_RAW_ROW PRIMARY KEY (MIGRATION_RAW_ROW_ID),
    CONSTRAINT FK_MIGRATION_RAW_ROW_BATCH FOREIGN KEY (MIGRATION_BATCH_ID)
        REFERENCES EFNS_DEV.RAW.MIGRATION_BATCH (MIGRATION_BATCH_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.MIGRATION_ID_MAP (
    MIGRATION_ID_MAP_ID VARCHAR(36) NOT NULL,
    MIGRATION_BATCH_ID VARCHAR(64) NOT NULL,
    SOURCE_ENTITY VARCHAR(100) NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    TARGET_ID VARCHAR(255) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_MIGRATION_ID_MAP PRIMARY KEY (MIGRATION_ID_MAP_ID),
    CONSTRAINT FK_MIGRATION_ID_MAP_BATCH FOREIGN KEY (MIGRATION_BATCH_ID)
        REFERENCES EFNS_DEV.RAW.MIGRATION_BATCH (MIGRATION_BATCH_ID),
    CONSTRAINT UQ_MIGRATION_SOURCE_ID UNIQUE (MIGRATION_BATCH_ID, SOURCE_ENTITY, SOURCE_ID)
);

USE ROLE SECURITYADMIN;

GRANT READ, WRITE ON STAGE EFNS_DEV.RAW.EIMS_MIGRATION_FILES TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE ON TABLE EFNS_DEV.RAW.MIGRATION_BATCH TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT ON TABLE EFNS_DEV.RAW.MIGRATION_FILE TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT ON TABLE EFNS_DEV.RAW.MIGRATION_RAW_ROW TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE ON TABLE EFNS_DEV.RAW.MIGRATION_ID_MAP TO ROLE EFNS_DEV_APP_OWNER;

-- Existing EFNS_DEV business tables are owned by ACCOUNTADMIN in the current
-- DEV account. The fixed-body procedure therefore uses that owner role while
-- exposing only one prefix-guarded operation to the application owner.
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE PROCEDURE EFNS_DEV.RAW.CLEANUP_SYNTHETIC_MIGRATION(BATCH_ID VARCHAR)
COPY GRANTS
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    IF (BATCH_ID NOT LIKE 'DEV_MIGRATION_%') THEN
        RETURN 'REJECTED_PREFIX';
    END IF;

    BEGIN TRANSACTION;
    DELETE FROM EFNS_DEV.CORE.PRODUCTION_RECORD WHERE PRODUCTION_ID IN
      (SELECT TARGET_ID FROM EFNS_DEV.RAW.MIGRATION_ID_MAP WHERE MIGRATION_BATCH_ID = :BATCH_ID AND SOURCE_ENTITY = 'PRODUCTION_RECORD');
    DELETE FROM EFNS_DEV.CORE.SALMONELLA_TEST WHERE SALMONELLA_TEST_ID IN
      (SELECT TARGET_ID FROM EFNS_DEV.RAW.MIGRATION_ID_MAP WHERE MIGRATION_BATCH_ID = :BATCH_ID AND SOURCE_ENTITY = 'SALMONELLA_TEST');
    DELETE FROM EFNS_DEV.CORE.QUOTA_TRANSACTION WHERE QUOTA_TRANSACTION_ID IN
      (SELECT TARGET_ID FROM EFNS_DEV.RAW.MIGRATION_ID_MAP WHERE MIGRATION_BATCH_ID = :BATCH_ID AND SOURCE_ENTITY = 'QUOTA_TRANSACTION');
    DELETE FROM EFNS_DEV.CORE.FLOCK_TRANSACTION WHERE FLOCK_TRANSACTION_ID IN
      (SELECT TARGET_ID FROM EFNS_DEV.RAW.MIGRATION_ID_MAP WHERE MIGRATION_BATCH_ID = :BATCH_ID AND SOURCE_ENTITY = 'FLOCK_TRANSACTION');
    DELETE FROM EFNS_DEV.CORE.FLOCK WHERE FLOCK_ID IN
      (SELECT TARGET_ID FROM EFNS_DEV.RAW.MIGRATION_ID_MAP WHERE MIGRATION_BATCH_ID = :BATCH_ID AND SOURCE_ENTITY = 'FLOCK');
    DELETE FROM EFNS_DEV.CORE.QUOTA_REGISTRATION WHERE QUOTA_ID IN
      (SELECT TARGET_ID FROM EFNS_DEV.RAW.MIGRATION_ID_MAP WHERE MIGRATION_BATCH_ID = :BATCH_ID AND SOURCE_ENTITY = 'QUOTA_REGISTRATION');
    DELETE FROM EFNS_DEV.CORE.FACILITY_DETAIL WHERE FACILITY_DETAIL_ID IN
      (SELECT TARGET_ID FROM EFNS_DEV.RAW.MIGRATION_ID_MAP WHERE MIGRATION_BATCH_ID = :BATCH_ID AND SOURCE_ENTITY = 'FACILITY_DETAIL');
    DELETE FROM EFNS_DEV.CORE.FACILITY WHERE FACILITY_ID IN
      (SELECT TARGET_ID FROM EFNS_DEV.RAW.MIGRATION_ID_MAP WHERE MIGRATION_BATCH_ID = :BATCH_ID AND SOURCE_ENTITY = 'FACILITY');
    DELETE FROM EFNS_DEV.CORE.ACCOUNT WHERE ACCOUNT_ID IN
      (SELECT TARGET_ID FROM EFNS_DEV.RAW.MIGRATION_ID_MAP WHERE MIGRATION_BATCH_ID = :BATCH_ID AND SOURCE_ENTITY = 'ACCOUNT');
    DELETE FROM EFNS_DEV.RAW.IMPORT_BATCH WHERE IMPORT_ID = :BATCH_ID;
    DELETE FROM EFNS_DEV.RAW.MIGRATION_RAW_ROW WHERE MIGRATION_BATCH_ID = :BATCH_ID;
    DELETE FROM EFNS_DEV.RAW.MIGRATION_FILE WHERE MIGRATION_BATCH_ID = :BATCH_ID;
    DELETE FROM EFNS_DEV.RAW.MIGRATION_ID_MAP WHERE MIGRATION_BATCH_ID = :BATCH_ID;
    DELETE FROM EFNS_DEV.RAW.MIGRATION_BATCH WHERE MIGRATION_BATCH_ID = :BATCH_ID;
    COMMIT;
    RETURN 'CLEANED';
EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RAISE;
END;
$$;

USE ROLE SECURITYADMIN;
GRANT USAGE ON PROCEDURE EFNS_DEV.RAW.CLEANUP_SYNTHETIC_MIGRATION(VARCHAR)
    TO ROLE EFNS_DEV_APP_OWNER;

-- No ordinary EFNS viewer/editor/admin/developer role receives stage or table access.

SELECT STATUS, COUNT(*) AS BATCH_COUNT
FROM EFNS_DEV.RAW.MIGRATION_BATCH
GROUP BY STATUS
ORDER BY STATUS;

SELECT COUNT(*) AS ORPHAN_RAW_ROWS
FROM EFNS_DEV.RAW.MIGRATION_RAW_ROW r
LEFT JOIN EFNS_DEV.RAW.MIGRATION_BATCH b
  ON b.MIGRATION_BATCH_ID = r.MIGRATION_BATCH_ID
WHERE b.MIGRATION_BATCH_ID IS NULL;
