-- EFNS DEV / additive support for the real 14-file EIMS Dataverse export.
-- Re-runnable: creates missing objects, adds missing columns, and only relaxes
-- constraints that reject valid historical source values.

USE ROLE SYSADMIN;
USE DATABASE EFNS_DEV;

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.CONTACT (
    CONTACT_ID VARCHAR(36) NOT NULL,
    ACCOUNT_ID VARCHAR(36),
    FULL_NAME VARCHAR(500) NOT NULL,
    FIRST_NAME VARCHAR(255),
    MIDDLE_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    JOB_TITLE VARCHAR(255),
    EMAIL VARCHAR(500),
    PHONE VARCHAR(100),
    MOBILE_PHONE VARCHAR(100),
    FAX VARCHAR(100),
    ADDRESS_LINE1 VARCHAR(500),
    ADDRESS_LINE2 VARCHAR(500),
    CITY VARCHAR(255),
    PROVINCE VARCHAR(100),
    POSTAL_CODE VARCHAR(50),
    COUNTRY_REGION VARCHAR(100),
    EIMS_CONTACT_NUMBER VARCHAR(100),
    LANGUAGE_PREFERENCE VARCHAR(100),
    PRIME_CONTACT BOOLEAN,
    STATUS VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_CONTACT PRIMARY KEY (CONTACT_ID),
    CONSTRAINT FK_CONTACT_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES EFNS_DEV.CORE.ACCOUNT (ACCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.QUOTA_ALLOCATION (
    QUOTA_ALLOCATION_ID VARCHAR(36) NOT NULL,
    ALLOCATION_COUNT NUMBER(18,4) NOT NULL,
    COMMENTS VARCHAR(4000),
    EFFECTIVE_DATE DATE NOT NULL,
    EIMS_ALLOCATION_ID VARCHAR(100),
    PROVINCE VARCHAR(100),
    QUOTA_TYPE VARCHAR(100) NOT NULL,
    STATUS VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_QUOTA_ALLOCATION PRIMARY KEY (QUOTA_ALLOCATION_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.CORE.DIM_EFC_DATE (
    DAY DATE NOT NULL,
    EFC_YEAR NUMBER(4,0),
    EFC_WEEK_NUMBER NUMBER(2,0),
    EFC_WEEK VARCHAR(50),
    EFC_WEEK_LABEL VARCHAR(100),
    EFC_LONG_NAME VARCHAR(255),
    EFC_PERIOD NUMBER(4,0),
    EFC_PERIOD_ALIAS VARCHAR(100),
    EFC_QUARTER NUMBER(2,0),
    ELEMENT_CODE VARCHAR(100),
    ELEMENT_CODES VARCHAR(16000),
    PREVIOUS_QUARTER VARCHAR(100),
    PREV_YEAR NUMBER(4,0),
    PREV_WEEK NUMBER(4,0),
    PREV_QUARTER NUMBER(4,0),
    DATE_VALUE DATE,
    MONTH_NUMBER NUMBER(2,0),
    MONTH_TEXT VARCHAR(20),
    DAYS_IN_MONTH NUMBER(2,0),
    YEAR_NUMBER NUMBER(4,0),
    YEAR_MONTH VARCHAR(20),
    QUARTER_NUMBER NUMBER(2,0),
    DAYS_IN_QUARTER NUMBER(3,0),
    YEAR_QUARTER VARCHAR(20),
    DAY_STRING VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_DIM_EFC_DATE PRIMARY KEY (DAY)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.MIGRATION_ERROR (
    MIGRATION_ERROR_ID VARCHAR(36) NOT NULL,
    MIGRATION_BATCH_ID VARCHAR(64) NOT NULL,
    SOURCE_FILENAME VARCHAR(500) NOT NULL,
    SOURCE_ENTITY VARCHAR(100) NOT NULL,
    SOURCE_ROW_NUMBER NUMBER(18,0) NOT NULL,
    FIELD_NAME VARCHAR(255),
    ERROR_CATEGORY VARCHAR(100) DEFAULT 'VALIDATION',
    ERROR_MESSAGE VARCHAR(2000) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_MIGRATION_ERROR PRIMARY KEY (MIGRATION_ERROR_ID),
    CONSTRAINT FK_MIGRATION_ERROR_BATCH FOREIGN KEY (MIGRATION_BATCH_ID)
        REFERENCES EFNS_DEV.RAW.MIGRATION_BATCH (MIGRATION_BATCH_ID)
);

CREATE TABLE IF NOT EXISTS EFNS_DEV.RAW.MIGRATION_RECONCILIATION (
    MIGRATION_RECONCILIATION_ID VARCHAR(36) NOT NULL,
    MIGRATION_BATCH_ID VARCHAR(64) NOT NULL,
    SOURCE_ENTITY VARCHAR(100) NOT NULL,
    SOURCE_ROWS NUMBER(18,0) NOT NULL,
    READY_ROWS NUMBER(18,0) NOT NULL,
    REJECTED_ROWS NUMBER(18,0) NOT NULL,
    INSERTED_ROWS NUMBER(18,0) NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    CONSTRAINT PK_MIGRATION_RECONCILIATION PRIMARY KEY (MIGRATION_RECONCILIATION_ID),
    CONSTRAINT FK_MIGRATION_RECONCILIATION_BATCH FOREIGN KEY (MIGRATION_BATCH_ID)
        REFERENCES EFNS_DEV.RAW.MIGRATION_BATCH (MIGRATION_BATCH_ID),
    CONSTRAINT UQ_MIGRATION_RECONCILIATION UNIQUE (MIGRATION_BATCH_ID, SOURCE_ENTITY)
);

ALTER TABLE IF EXISTS EFNS_DEV.CORE.FARM_LOCATION ADD COLUMN IF NOT EXISTS FAX VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FARM_LOCATION ADD COLUMN IF NOT EXISTS EIMS_LOCATION_ID VARCHAR(100);

ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY ADD COLUMN IF NOT EXISTS FARM_LOCATION_ID VARCHAR(36);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY ADD COLUMN IF NOT EXISTS HOUSING_SYSTEM VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY ADD COLUMN IF NOT EXISTS RENOVATION_DATE DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY ADD COLUMN IF NOT EXISTS FACILITY_QUOTA NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY ADD COLUMN IF NOT EXISTS MANURE_DISPOSAL VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY ADD COLUMN IF NOT EXISTS COMMENTS VARCHAR(4000);

ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS EIMS_FACILITY_DETAIL_ID VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS BIRD_COLOUR VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS BIRDS_HOUSED NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS CAGE_BRAND VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS DATE_INSTALLED DATE;
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS HEIGHT NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS HIGHEST_BIRDS_PER_CAGE NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS LENGTH NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS NUMBER_OF_CAGES NUMBER(18,0);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS SQUARE_INCHES NUMBER(18,4);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.FACILITY_DETAIL ADD COLUMN IF NOT EXISTS WIDTH NUMBER(18,4);

ALTER TABLE IF EXISTS EFNS_DEV.CORE.SALMONELLA_TEST ADD COLUMN IF NOT EXISTS TEST_TYPE VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE ADD COLUMN IF NOT EXISTS TEST_AREA VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE ADD COLUMN IF NOT EXISTS SEROTYPE VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE ADD COLUMN IF NOT EXISTS PHAGE VARCHAR(255);
ALTER TABLE IF EXISTS EFNS_DEV.CORE.SALMONELLA_TEST_SAMPLE ADD COLUMN IF NOT EXISTS STATUS VARCHAR(100);
ALTER TABLE IF EXISTS EFNS_DEV.RAW.MIGRATION_ERROR ADD COLUMN IF NOT EXISTS ERROR_CATEGORY VARCHAR(100);

BEGIN
    IF (EXISTS (
        SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'FLOCK'
          AND COLUMN_NAME = 'FACILITY_ID' AND IS_NULLABLE = 'NO'
    )) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.FLOCK ALTER COLUMN FACILITY_ID DROP NOT NULL';
    END IF;
    IF (EXISTS (
        SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'QUOTA_TRANSACTION'
          AND COLUMN_NAME = 'RELATED_ACCOUNT_ID' AND IS_NULLABLE = 'NO'
    )) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.QUOTA_TRANSACTION ALTER COLUMN RELATED_ACCOUNT_ID DROP NOT NULL';
    END IF;
    IF (EXISTS (
        SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'SALMONELLA_TEST'
          AND COLUMN_NAME = 'NUMBER_OF_SAMPLES' AND IS_NULLABLE = 'NO'
    )) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.SALMONELLA_TEST ALTER COLUMN NUMBER_OF_SAMPLES DROP NOT NULL';
    END IF;
    IF (EXISTS (
        SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'SALMONELLA_TEST'
          AND COLUMN_NAME = 'TEST_RESULT' AND IS_NULLABLE = 'NO'
    )) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.SALMONELLA_TEST ALTER COLUMN TEST_RESULT DROP NOT NULL';
    END IF;
    IF (EXISTS (
        SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS
        WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'QUOTA_TRANSACTION'
          AND CONSTRAINT_NAME = 'CK_QUOTA_TRANSACTION_COUNT'
    )) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.QUOTA_TRANSACTION DROP CONSTRAINT CK_QUOTA_TRANSACTION_COUNT';
    END IF;
    IF (EXISTS (
        SELECT 1 FROM EFNS_DEV.INFORMATION_SCHEMA.TABLE_CONSTRAINTS
        WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME = 'SALMONELLA_TEST'
          AND CONSTRAINT_NAME = 'CK_SALMONELLA_SAMPLE_COUNT'
    )) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EFNS_DEV.CORE.SALMONELLA_TEST DROP CONSTRAINT CK_SALMONELLA_SAMPLE_COUNT';
    END IF;
END;

USE ROLE SECURITYADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE EFNS_DEV.CORE.CONTACT TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE EFNS_DEV.CORE.QUOTA_ALLOCATION TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE ON TABLE EFNS_DEV.CORE.DIM_EFC_DATE TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT ON TABLE EFNS_DEV.RAW.MIGRATION_ERROR TO ROLE EFNS_DEV_APP_OWNER;
GRANT SELECT, INSERT, UPDATE ON TABLE EFNS_DEV.RAW.MIGRATION_RECONCILIATION TO ROLE EFNS_DEV_APP_OWNER;

USE ROLE SYSADMIN;
